# Day 09. Exercise 00
# Regularization

## 0. Imports

In [41]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import joblib

## 1. Preprocessing

1. Read the file `dayofweek.csv` that you used in the previous day to a dataframe.
2. Using `train_test_split` with parameters `test_size=0.2`, `random_state=21` get `X_train`, `y_train`, `X_test`, `y_test`. Use the additional parameter `stratify`.

In [42]:
df = pd.read_csv('../data/dayofweek.csv')
df

,numTrials,hour,uid_user_0,uid_user_1,uid_user_10,uid_user_11,uid_user_12,uid_user_13,uid_user_14,uid_user_15,...,labname_lab03,labname_lab03s,labname_lab05s,labname_laba04,labname_laba04s,labname_laba05,labname_laba06,labname_laba06s,labname_project1,dayofweek
0,-0.788667,-2.562352,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4.0
1,-0.756764,-2.562352,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4.0
2,-0.724861,-2.562352,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4.0
3,-0.692958,-2.562352,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4.0
4,-0.661055,-2.562352,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1681,-0.533442,0.945382,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,3.0
1682,-0.629151,0.945382,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,3.0
1683,-0.597248,0.945382,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,3.0
1684,-0.565345,0.945382,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,3.0
1685,-0.533442,0.945382,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,3.0

In [43]:
X = df.drop(columns=['dayofweek'])
y = df.dayofweek

In [44]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=21, stratify=y)

## 2. Logreg regularization

### a. Default regularization

1. Train a baseline model with the only parameters `random_state=21`, `fit_intercept=False`.
2. Use stratified K-fold cross-validation with `10` splits to evaluate the accuracy of the model


The result of the code where you trained and evaluated the baseline model should be exactly like this (use `%%time` to get the info about how long it took to run the cell):

```
train -  0.62902   |   valid -  0.59259
train -  0.64633   |   valid -  0.62963
train -  0.63479   |   valid -  0.56296
train -  0.65622   |   valid -  0.61481
train -  0.63397   |   valid -  0.57778
train -  0.64056   |   valid -  0.59259
train -  0.64138   |   valid -  0.65926
train -  0.65952   |   valid -  0.56296
train -  0.64333   |   valid -  0.59701
train -  0.63674   |   valid -  0.62687
Average accuracy on crossval is 0.60165
Std is 0.02943
```

In [45]:
def crossval(X, y, model, n_splits=10):
    skf = StratifiedKFold(n_splits=n_splits)
    test_accuracy = []

    for train_index, test_index in skf.split(X, y):
        X_train, X_test = X.iloc[train_index], X.iloc[test_index]
        y_train, y_test = y.iloc[train_index], y.iloc[test_index]

        model.fit(X_train, y_train)

        train_score = model.score(X_train, y_train)
        test_score = model.score(X_test, y_test)
        test_accuracy.append(test_score)
        print(f'train - {train_score:.5f}  |  test - {test_score:.5f}')

    print(f'Average accuracy on crossval is {np.mean(test_accuracy):.5f}')
    print(f'Std id {np.std(test_accuracy):.5f}')

In [46]:
logreg_model = LogisticRegression(random_state=21, fit_intercept=False)

In [47]:
%%time
crossval(X_train, y_train, logreg_model, 10)

train - 0.62819  |  test - 0.59259
train - 0.64716  |  test - 0.62963
train - 0.63479  |  test - 0.57037
train - 0.65540  |  test - 0.61481
train - 0.63314  |  test - 0.57778
train - 0.64056  |  test - 0.59259
train - 0.64221  |  test - 0.65926
train - 0.65952  |  test - 0.56296
train - 0.64333  |  test - 0.59701
train - 0.63591  |  test - 0.62687
Average accuracy on crossval is 0.60239
Std id 0.02852
CPU times: total: 328 ms
Wall time: 234 ms

### b. Optimizing regularization parameters

1. In the cells below try different values of penalty: `none`, `l1`, `l2` – you can change the values of solver too.

In [48]:
logreg_model = LogisticRegression(random_state=21, fit_intercept=False, penalty='l1', solver='liblinear')
crossval(X, y, logreg_model, 10)

train - 0.66842  |  test - 0.20118
train - 0.67106  |  test - 0.45562
train - 0.64338  |  test - 0.53846
train - 0.62887  |  test - 0.59763
train - 0.63283  |  test - 0.64497
train - 0.62030  |  test - 0.68047
train - 0.60474  |  test - 0.61905
train - 0.63175  |  test - 0.35119
train - 0.63900  |  test - 0.26786
train - 0.65217  |  test - 0.16667
Average accuracy on crossval is 0.45231
Std id 0.18288

In [49]:
logreg_model = LogisticRegression(random_state=21, fit_intercept=False, penalty='l2', solver='liblinear')
crossval(X, y, logreg_model, 10)

train - 0.65920  |  test - 0.22485
train - 0.65524  |  test - 0.45562
train - 0.63546  |  test - 0.49112
train - 0.62426  |  test - 0.59172
train - 0.63085  |  test - 0.64497
train - 0.61833  |  test - 0.68639
train - 0.60079  |  test - 0.60119
train - 0.62714  |  test - 0.35119
train - 0.63636  |  test - 0.26786
train - 0.64625  |  test - 0.21429
Average accuracy on crossval is 0.45292
Std id 0.16961

In [50]:
logreg_model = LogisticRegression(random_state=21, fit_intercept=False, penalty='l2')
crossval(X, y, logreg_model, 10)

train - 0.68095  |  test - 0.25444
train - 0.68029  |  test - 0.42604
train - 0.64931  |  test - 0.49112
train - 0.64008  |  test - 0.56805
train - 0.64865  |  test - 0.64497
train - 0.63151  |  test - 0.68047
train - 0.61726  |  test - 0.59524
train - 0.64822  |  test - 0.35119
train - 0.65679  |  test - 0.29762
train - 0.66733  |  test - 0.19643
Average accuracy on crossval is 0.45056
Std id 0.16247

In [51]:
logreg_model = LogisticRegression(random_state=21, fit_intercept=False, penalty='l2', solver='sag')
crossval(X, y, logreg_model, 10)

train - 0.68095  |  test - 0.25444
train - 0.68029  |  test - 0.42604
train - 0.64865  |  test - 0.49112
train - 0.63942  |  test - 0.56805
train - 0.64799  |  test - 0.64497
train - 0.63283  |  test - 0.68047
train - 0.61792  |  test - 0.59524
train - 0.64822  |  test - 0.35119
train - 0.65613  |  test - 0.29762
train - 0.66798  |  test - 0.19643
Average accuracy on crossval is 0.45056
Std id 0.16247

## 3. SVM regularization

### a. Default regularization

1. Train a baseline model with the only parameters `probability=True`, `kernel='linear'`, `random_state=21`.
2. Use stratified K-fold cross-validation with `10` splits to evaluate the accuracy of the model.
3. The format of the result of the code where you trained and evaluated the baseline model should be similar to what you have got for the logreg.

In [52]:
svc_model = SVC(probability=True, kernel='linear', random_state=21)

In [53]:
%%time
crossval(X_train, y_train, svc_model, 10)

train - 0.70486  |  test - 0.65926
train - 0.69662  |  test - 0.75556
train - 0.69415  |  test - 0.62222
train - 0.70239  |  test - 0.65185
train - 0.69085  |  test - 0.65185
train - 0.68920  |  test - 0.64444
train - 0.69250  |  test - 0.72593
train - 0.70074  |  test - 0.62222
train - 0.69605  |  test - 0.61940
train - 0.71087  |  test - 0.63433
Average accuracy on crossval is 0.65871
Std id 0.04359
CPU times: total: 1.98 s
Wall time: 2.02 s

### b. Optimizing regularization parameters

1. In the cells below try different values of the parameter `C`.

In [54]:
svc_model = SVC(probability=True, kernel='linear', random_state=21, C=0.5)
crossval(X_train, y_train, svc_model, 10)

train - 0.66694  |  test - 0.63704
train - 0.66612  |  test - 0.73333
train - 0.67271  |  test - 0.60741
train - 0.67354  |  test - 0.62963
train - 0.67766  |  test - 0.64444
train - 0.66529  |  test - 0.61481
train - 0.66200  |  test - 0.68889
train - 0.66529  |  test - 0.57037
train - 0.67463  |  test - 0.59701
train - 0.66804  |  test - 0.61194
Average accuracy on crossval is 0.63349
Std id 0.04471

In [55]:
svc_model = SVC(probability=True, kernel='linear', random_state=21, C=0.2)
crossval(X_train, y_train, svc_model, 10)

train - 0.63149  |  test - 0.60000
train - 0.61748  |  test - 0.58519
train - 0.63561  |  test - 0.60741
train - 0.64551  |  test - 0.60000
train - 0.64468  |  test - 0.60000
train - 0.65128  |  test - 0.59259
train - 0.63397  |  test - 0.65926
train - 0.62737  |  test - 0.57778
train - 0.62438  |  test - 0.55970
train - 0.63180  |  test - 0.61194
Average accuracy on crossval is 0.59939
Std id 0.02469

In [56]:
svc_model = SVC(probability=True, kernel='linear', random_state=21, C=0.8)
crossval(X_train, y_train, svc_model, 10)

train - 0.70239  |  test - 0.67407
train - 0.69497  |  test - 0.75556
train - 0.69002  |  test - 0.63704
train - 0.69415  |  test - 0.65185
train - 0.69332  |  test - 0.65926
train - 0.68096  |  test - 0.64444
train - 0.68838  |  test - 0.72593
train - 0.69415  |  test - 0.62222
train - 0.69440  |  test - 0.61194
train - 0.69440  |  test - 0.63433
Average accuracy on crossval is 0.66166
Std id 0.04345

In [57]:
svc_model = SVC(probability=True, kernel='linear', random_state=21, C=1.5)
crossval(X_train, y_train, svc_model, 10)

train - 0.70734  |  test - 0.65926
train - 0.70486  |  test - 0.74815
train - 0.74361  |  test - 0.64444
train - 0.70816  |  test - 0.67407
train - 0.70239  |  test - 0.67407
train - 0.69909  |  test - 0.64444
train - 0.70239  |  test - 0.72593
train - 0.70239  |  test - 0.62963
train - 0.70840  |  test - 0.64925
train - 0.71911  |  test - 0.64179
Average accuracy on crossval is 0.66910
Std id 0.03679

In [58]:
svc_model = SVC(probability=True, kernel='linear', random_state=21, C=10)
crossval(X_train, y_train, svc_model, 10)

train - 0.75021  |  test - 0.72593
train - 0.77741  |  test - 0.82963
train - 0.78566  |  test - 0.68148
train - 0.76834  |  test - 0.73333
train - 0.75185  |  test - 0.77778
train - 0.75598  |  test - 0.68889
train - 0.76257  |  test - 0.74074
train - 0.77411  |  test - 0.68889
train - 0.78254  |  test - 0.71642
train - 0.78418  |  test - 0.69403
Average accuracy on crossval is 0.72771
Std id 0.04417

## 4. Tree

### a. Default regularization

1. Train a baseline model with the only parameter `max_depth=10` and `random_state=21`.
2. Use stratified K-fold cross-validation with `10` splits to evaluate the accuracy of the model.
3. The format of the result of the code where you trained and evaluated the baseline model should be similar to what you have got for the logreg.

In [59]:
tree_model = DecisionTreeClassifier(max_depth=10, random_state=21)

In [60]:
%%time
crossval(X_train, y_train, tree_model)

train - 0.81039  |  test - 0.74074
train - 0.77741  |  test - 0.74074
train - 0.83347  |  test - 0.70370
train - 0.79720  |  test - 0.76296
train - 0.82440  |  test - 0.75556
train - 0.80379  |  test - 0.68889
train - 0.80709  |  test - 0.76296
train - 0.80132  |  test - 0.65926
train - 0.80807  |  test - 0.75373
train - 0.80478  |  test - 0.68657
Average accuracy on crossval is 0.72551
Std id 0.03562
CPU times: total: 46.9 ms
Wall time: 60 ms

### b. Optimizing regularization parameters

1. In the cells below try different values of the parameter `max_depth`.
2. As a bonus, play with other regularization parameters trying to find the best combination.

In [61]:
tree_model = DecisionTreeClassifier(max_depth=5, random_state=21)
crossval(X_train, y_train, tree_model)

train - 0.59522  |  test - 0.53333
train - 0.56307  |  test - 0.53333
train - 0.60181  |  test - 0.55556
train - 0.59604  |  test - 0.57037
train - 0.60264  |  test - 0.57778
train - 0.57955  |  test - 0.53333
train - 0.58368  |  test - 0.54815
train - 0.59275  |  test - 0.51111
train - 0.58237  |  test - 0.56716
train - 0.60132  |  test - 0.50000
Average accuracy on crossval is 0.54301
Std id 0.02423

In [62]:
tree_model = DecisionTreeClassifier(max_depth=20, random_state=21)
crossval(X_train, y_train, tree_model)

train - 0.98846  |  test - 0.86667
train - 0.99011  |  test - 0.91111
train - 0.98681  |  test - 0.85926
train - 0.98763  |  test - 0.91111
train - 0.98928  |  test - 0.88148
train - 0.98186  |  test - 0.85926
train - 0.98846  |  test - 0.91852
train - 0.99176  |  test - 0.89630
train - 0.99094  |  test - 0.88060
train - 0.98847  |  test - 0.88060
Average accuracy on crossval is 0.88649
Std id 0.02075

In [63]:
tree_model = DecisionTreeClassifier(max_depth=10, random_state=21, min_samples_split=5)
crossval(X_train, y_train, tree_model)

train - 0.80709  |  test - 0.74815
train - 0.76834  |  test - 0.74074
train - 0.82605  |  test - 0.69630
train - 0.79390  |  test - 0.76296
train - 0.81863  |  test - 0.76296
train - 0.79885  |  test - 0.68889
train - 0.80049  |  test - 0.75556
train - 0.79555  |  test - 0.65185
train - 0.80066  |  test - 0.75373
train - 0.80148  |  test - 0.68657
Average accuracy on crossval is 0.72477
Std id 0.03792

## 5. Random forest

### a. Default regularization

1. Train a baseline model with the only parameters `n_estimators=50`, `max_depth=14`, `random_state=21`.
2. Use stratified K-fold cross-validation with `10` splits to evaluate the accuracy of the model.
3. The format of the result of the code where you trained and evaluated the baseline model should be similar to what you have got for the logreg.

In [64]:
forest_model = RandomForestClassifier(n_estimators=50, max_depth=14, random_state=21)

In [65]:
%%time
crossval(X_train, y_train, forest_model)

train - 0.96455  |  test - 0.88148
train - 0.96208  |  test - 0.91852
train - 0.96785  |  test - 0.86667
train - 0.96455  |  test - 0.89630
train - 0.96538  |  test - 0.91111
train - 0.96538  |  test - 0.88148
train - 0.97115  |  test - 0.91852
train - 0.96867  |  test - 0.85185
train - 0.97364  |  test - 0.88060
train - 0.97941  |  test - 0.86567
Average accuracy on crossval is 0.88722
Std id 0.02204
CPU times: total: 703 ms
Wall time: 744 ms

### b. Optimizing regularization parameters

1. In the new cells try different values of the parameters `max_depth` and `n_estimators`.
2. As a bonus, play with other regularization parameters trying to find the best combination.

In [66]:
forest_model = RandomForestClassifier(n_estimators=100, max_depth=30, random_state=21)
crossval(X_train, y_train, forest_model)

train - 1.00000  |  test - 0.90370
train - 1.00000  |  test - 0.94074
train - 1.00000  |  test - 0.91852
train - 1.00000  |  test - 0.92593
train - 1.00000  |  test - 0.91111
train - 1.00000  |  test - 0.90370
train - 0.99918  |  test - 0.92593
train - 0.99918  |  test - 0.90370
train - 1.00000  |  test - 0.91045
train - 1.00000  |  test - 0.90299
Average accuracy on crossval is 0.91468
Std id 0.01215

In [67]:
forest_model = RandomForestClassifier(n_estimators=150, max_depth=20, random_state=21)
crossval(X_train, y_train, forest_model)

train - 0.99835  |  test - 0.90370
train - 0.99835  |  test - 0.94815
train - 0.99753  |  test - 0.88889
train - 0.99835  |  test - 0.93333
train - 0.99753  |  test - 0.91111
train - 0.99670  |  test - 0.88889
train - 0.99753  |  test - 0.91852
train - 0.99753  |  test - 0.89630
train - 0.99918  |  test - 0.92537
train - 0.99753  |  test - 0.88060
Average accuracy on crossval is 0.90949
Std id 0.02071

In [68]:
forest_model = RandomForestClassifier(n_estimators=200, max_depth=30, random_state=21)
crossval(X_train, y_train, forest_model)

train - 1.00000  |  test - 0.90370
train - 1.00000  |  test - 0.94815
train - 1.00000  |  test - 0.91111
train - 1.00000  |  test - 0.93333
train - 1.00000  |  test - 0.91111
train - 1.00000  |  test - 0.90370
train - 1.00000  |  test - 0.92593
train - 1.00000  |  test - 0.90370
train - 1.00000  |  test - 0.91791
train - 1.00000  |  test - 0.90299
Average accuracy on crossval is 0.91616
Std id 0.01451

In [69]:
forest_model = RandomForestClassifier(n_estimators=100, max_depth=50, random_state=21)
crossval(X_train, y_train, forest_model)

train - 1.00000  |  test - 0.89630
train - 1.00000  |  test - 0.95556
train - 1.00000  |  test - 0.91111
train - 1.00000  |  test - 0.93333
train - 1.00000  |  test - 0.91111
train - 1.00000  |  test - 0.89630
train - 1.00000  |  test - 0.91852
train - 1.00000  |  test - 0.90370
train - 1.00000  |  test - 0.91791
train - 1.00000  |  test - 0.90299
Average accuracy on crossval is 0.91468
Std id 0.01733

In [70]:
forest_model = RandomForestClassifier(n_estimators=100, max_depth=7, random_state=21)
crossval(X_train, y_train, forest_model)

train - 0.72135  |  test - 0.65926
train - 0.72630  |  test - 0.74074
train - 0.72053  |  test - 0.64444
train - 0.73537  |  test - 0.67407
train - 0.72465  |  test - 0.72593
train - 0.73866  |  test - 0.67407
train - 0.72795  |  test - 0.71852
train - 0.74444  |  test - 0.64444
train - 0.72817  |  test - 0.67164
train - 0.71911  |  test - 0.64925
Average accuracy on crossval is 0.68024
Std id 0.03365

In [71]:
forest_model = RandomForestClassifier(n_estimators=60, max_depth=20, random_state=21)
crossval(X_train, y_train, forest_model)

train - 0.99670  |  test - 0.91111
train - 0.99753  |  test - 0.95556
train - 0.99588  |  test - 0.88148
train - 0.99753  |  test - 0.93333
train - 0.99505  |  test - 0.91852
train - 0.99588  |  test - 0.88889
train - 0.99505  |  test - 0.91852
train - 0.99753  |  test - 0.89630
train - 0.99918  |  test - 0.93284
train - 0.99671  |  test - 0.88806
Average accuracy on crossval is 0.91246
Std id 0.02271

## 6. Predictions

1. Choose the best model and use it to make predictions for the test dataset.
2. Calculate the final accuracy.
3. Analyze: for which weekday your model makes the most errors (in % of the total number of samples of that class in your test dataset).
4. Save the model.

In [72]:
best_model = RandomForestClassifier(n_estimators=60, max_depth=20, random_state=21)
best_model.fit(X_train, y_train)

RandomForestClassifier(max_depth=20, n_estimators=60, random_state=21)

In [73]:
best_predict = best_model.predict(X_test)

In [74]:
accuracy_score(y_test, best_predict)

0.9230769230769231

In [75]:
number_of_samples = dict(y_test.value_counts())

In [76]:
analyze_table = y_test.reset_index().drop(columns=['index'])
analyze_table['predict'] = best_predict
analyze_table['error'] = analyze_table['predict'] != analyze_table['dayofweek']
analyze_table

     dayofweek  predict  error
0          1.0      1.0  False
1          5.0      5.0  False
2          6.0      6.0  False
3          3.0      3.0  False
4          2.0      2.0  False
..         ...      ...    ...
333        3.0      3.0  False
334        1.0      1.0  False
335        2.0      2.0  False
336        1.0      1.0  False
337        2.0      2.0  False

[338 rows x 3 columns]

In [77]:
final_talbe_for_analuze = pd.DataFrame(analyze_table.groupby('dayofweek')['error'].sum()).reset_index()
final_talbe_for_analuze['all_number'] = [number_of_samples[x] for x in range(0,7)]
final_talbe_for_analuze

   dayofweek  error  all_number
0        0.0      7          27
1        1.0      8          55
2        2.0      2          30
3        3.0      2          80
4        4.0      3          21
5        5.0      3          54
6        6.0      1          71

In [78]:
final_talbe_for_analuze['percetn_errors'] = (final_talbe_for_analuze.error / final_talbe_for_analuze.all_number) * 100

In [79]:
final_talbe_for_analuze

   dayofweek  error  all_number  percetn_errors
0        0.0      7          27       25.925926
1        1.0      8          55       14.545455
2        2.0      2          30        6.666667
3        3.0      2          80        2.500000
4        4.0      3          21       14.285714
5        5.0      3          54        5.555556
6        6.0      1          71        1.408451

In [80]:
joblib.dump(best_model, 'random_forest_best.joblib')

['random_forest_best.joblib']