In [1]:
import pandas as pd
import sqlite3

## create a connection to the database using the library sqlite3

In [2]:
conn = sqlite3.connect('../data/checking-logs.sqlite')

## create a new table datamart in the database by joining the tables pageviews and checker using only one query

In [3]:
datamart = pd.read_sql('''
SELECT c.uid as uid, c.labname as labname,
    c.timestamp as first_commit_ts,
    p.dt as first_view_ts
FROM checker c
    LEFT JOIN (
        SELECT uid, MIN(datetime) as dt 
        FROM pageviews
        GROUP BY uid      
        ) p
    USING(uid)
WHERE c.status = 'ready' AND
    c.numTrials = 1 AND
    c.labname IN ('laba04', 'laba04s', 'laba05', 'laba06', 'laba06s', 'project1') AND
    (c.uid LIKE 'user_%')
''', conn, parse_dates= ['first_commit_ts', 'first_view_ts'])
datamart

         uid   labname            first_commit_ts              first_view_ts
0     user_4  project1 2020-04-17 05:19:02.744528                        NaT
1     user_4    laba04 2020-04-17 11:33:17.366400                        NaT
2     user_4   laba04s 2020-04-17 11:48:41.992466                        NaT
3    user_17  project1 2020-04-18 07:56:45.408648 2020-04-18 10:56:55.833899
4    user_30    laba04 2020-04-18 13:36:53.971502 2020-04-17 22:46:26.785035
..       ...       ...                        ...                        ...
135  user_23    laba06 2020-05-21 08:34:10.517205                        NaT
136  user_19   laba06s 2020-05-21 13:27:06.705881 2020-04-21 20:30:38.034966
137  user_23   laba06s 2020-05-21 14:29:15.709568                        NaT
138  user_17    laba06 2020-05-21 15:21:31.567615 2020-04-18 10:56:55.833899
139  user_17   laba06s 2020-05-21 17:39:17.783615 2020-04-18 10:56:55.833899

[140 rows x 4 columns]

In [4]:
datamart.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 140 entries, 0 to 139
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   uid              140 non-null    object
 1   labname          140 non-null    object
 2   first_commit_ts  140 non-null    datetime64[ns]
 3   first_view_ts    59 non-null     datetime64[ns]
dtypes: datetime64[ns](2), object(2)
memory usage: 4.5+ KB

## using Pandas methods, create two dataframes: test and control

In [5]:
test = datamart[datamart['first_view_ts'].notnull()]
test.info()

<class 'pandas.core.frame.DataFrame'>
Index: 59 entries, 3 to 139
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   uid              59 non-null     object
 1   labname          59 non-null     object
 2   first_commit_ts  59 non-null     datetime64[ns]
 3   first_view_ts    59 non-null     datetime64[ns]
dtypes: datetime64[ns](2), object(2)
memory usage: 2.3+ KB

In [6]:
control = datamart[datamart.first_view_ts.isnull()]
control.info()

<class 'pandas.core.frame.DataFrame'>
Index: 81 entries, 0 to 137
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   uid              81 non-null     object
 1   labname          81 non-null     object
 2   first_commit_ts  81 non-null     datetime64[ns]
 3   first_view_ts    0 non-null      datetime64[ns]
dtypes: datetime64[ns](2), object(2)
memory usage: 3.2+ KB

In [7]:
control.first_view_ts = test.first_view_ts.mean()
control.head()

C:\Users\User\AppData\Local\Temp\ipykernel_9172\2889034277.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  control.first_view_ts = test.first_view_ts.mean()

      uid   labname            first_commit_ts                 first_view_ts
0  user_4  project1 2020-04-17 05:19:02.744528 2020-04-27 00:40:05.761783552
1  user_4    laba04 2020-04-17 11:33:17.366400 2020-04-27 00:40:05.761783552
2  user_4   laba04s 2020-04-17 11:48:41.992466 2020-04-27 00:40:05.761783552
5  user_2    laba04 2020-04-18 13:42:35.482008 2020-04-27 00:40:05.761783552
6  user_2   laba04s 2020-04-18 13:51:22.291271 2020-04-27 00:40:05.761783552

In [8]:
test.to_sql('test', conn, index=False, if_exists='replace')
control.to_sql('control', conn, index=False, if_exists='replace')

81

## close the connection

In [9]:
conn.close()