## read_csv

In [11]:
import pandas as pd

In [12]:
df = pd.read_csv('../data/feed-views.log', sep='\t', skiprows=[2, 3], skipfooter=2, engine='python', names=['datetime', 'user'], index_col=0)

In [13]:
df.head()

                              user
datetime
2020-04-17 12:01:08.463179   artem
2020-04-17 12:01:23.743946   artem
2020-04-17 12:35:52.735016   artem
2020-04-17 12:36:21.401412  oksana
2020-04-17 12:36:22.023355  oksana

In [14]:
df.tail()

                                 user
datetime
2020-05-21 16:36:40.915488  ekaterina
2020-05-21 17:49:36.429237      maxim
2020-05-21 18:45:20.441142  valentina
2020-05-21 23:03:06.457819      maxim
2020-05-21 23:23:49.995349      pavel

## Rename datetime to date_time

In [15]:
df.columns

Index(['user'], dtype='object')

In [16]:
df.index.name = 'date_time'
df

                                 user
date_time
2020-04-17 12:01:08.463179      artem
2020-04-17 12:01:23.743946      artem
2020-04-17 12:35:52.735016      artem
2020-04-17 12:36:21.401412     oksana
2020-04-17 12:36:22.023355     oksana
...                               ...
2020-05-21 16:36:40.915488  ekaterina
2020-05-21 17:49:36.429237      maxim
2020-05-21 18:45:20.441142  valentina
2020-05-21 23:03:06.457819      maxim
2020-05-21 23:23:49.995349      pavel

[1072 rows x 1 columns]

## to_csv

In [17]:
df.to_csv(path_or_buf='../data/feed-views-semicolon.log', sep=';')

In [18]:
df.count()

user    1072
dtype: int64

In [19]:
df2 = pd.read_csv('../data/feed-views-semicolon.log')

In [20]:
df2.head()

                      date_time;user
0   2020-04-17 12:01:08.463179;artem
1   2020-04-17 12:01:23.743946;artem
2   2020-04-17 12:35:52.735016;artem
3  2020-04-17 12:36:21.401412;oksana
4  2020-04-17 12:36:22.023355;oksana