In [1]:
import pandas as pd

## download and read the CSV file and make ID the index column

In [2]:
df = pd.read_csv('../data/auto.csv', index_col=0)
df.head(10)

       CarNumber  Make_n_model  Refund   Fines  History
ID
0   Y163O8161RUS    Ford Focus     2.0  3200.0      NaN
1    E432XX77RUS  Toyota Camry     1.0  6500.0      NaN
2    7184TT36RUS    Ford Focus     1.0  2100.0      NaN
3   X582HE161RUS    Ford Focus     2.0  2000.0      NaN
4   E34877152RUS    Ford Focus     2.0  6100.0      NaN
5   92918M178RUS    Ford Focus     1.0  5700.0      NaN
6   E53488152RUS    Ford Focus     2.0  1800.0      NaN
7   X4128H125RUS    Ford Focus     1.0     NaN      2.0
8   C593EY154RUS    Ford Focus     1.0  1000.0      NaN
9   8049HT125RUS    Ford Focus     1.0   500.0      NaN

## count the number of observations using the method count()

In [3]:
df.count()

CarNumber       931
Make_n_model    931
Refund          914
Fines           869
History          82
dtype: int64

In [4]:
df.drop_duplicates(['CarNumber', 'Make_n_model', 'Fines'], keep='last', inplace=True)

In [5]:
df.count()

CarNumber       725
Make_n_model    725
Refund          713
Fines           665
History          65
dtype: int64

## work with missing values

In [6]:
df.isna().sum()

CarNumber         0
Make_n_model      0
Refund           12
Fines            60
History         660
dtype: int64

In [7]:
df.dropna(axis=1, thresh=500, inplace=True)

In [8]:
df.isna().sum()

CarNumber        0
Make_n_model     0
Refund          12
Fines           60
dtype: int64

In [9]:
df['Refund'] = df['Refund'].ffill()

In [10]:
df.isna().sum()

CarNumber        0
Make_n_model     0
Refund           0
Fines           60
dtype: int64

In [11]:
df['Fines'] = df['Fines'].fillna(value=df['Fines'].mean(skipna=True))

In [12]:
df.isna().sum()

CarNumber       0
Make_n_model    0
Refund          0
Fines           0
dtype: int64

## split and parse the make and model

In [13]:
make_and_model = df['Make_n_model'].apply(lambda x: pd.Series([x.split()[0], x.split()[1]], index=['Make', 'Model']) if len(x.split()) == 2 else pd.Series([x.split()[0], None], index=['Make', 'Model']))

In [14]:
df = pd.concat([df, make_and_model], axis=1)
df

        CarNumber    Make_n_model  Refund         Fines    Make    Model
ID
0    Y163O8161RUS      Ford Focus     2.0   3200.000000    Ford    Focus
1     E432XX77RUS    Toyota Camry     1.0   6500.000000  Toyota    Camry
2     7184TT36RUS      Ford Focus     1.0   2100.000000    Ford    Focus
3    X582HE161RUS      Ford Focus     2.0   2000.000000    Ford    Focus
5    92918M178RUS      Ford Focus     1.0   5700.000000    Ford    Focus
..            ...             ...     ...           ...     ...      ...
926  Y163O8161RUS      Ford Focus     2.0   1600.000000    Ford    Focus
927  M0309X197RUS      Ford Focus     1.0  22300.000000    Ford    Focus
928  O673E8197RUS      Ford Focus     2.0    600.000000    Ford    Focus
929  8610T8154RUS      Ford Focus     1.0   2000.000000    Ford    Focus
930  H419XE197RUS  Toyota Corolla     2.0   8594.586466  Toyota  Corolla

[725 rows x 6 columns]

In [15]:
df.drop('Make_n_model', axis=1, inplace=True)

In [16]:
df

        CarNumber  Refund         Fines    Make    Model
ID
0    Y163O8161RUS     2.0   3200.000000    Ford    Focus
1     E432XX77RUS     1.0   6500.000000  Toyota    Camry
2     7184TT36RUS     1.0   2100.000000    Ford    Focus
3    X582HE161RUS     2.0   2000.000000    Ford    Focus
5    92918M178RUS     1.0   5700.000000    Ford    Focus
..            ...     ...           ...     ...      ...
926  Y163O8161RUS     2.0   1600.000000    Ford    Focus
927  M0309X197RUS     1.0  22300.000000    Ford    Focus
928  O673E8197RUS     2.0    600.000000    Ford    Focus
929  8610T8154RUS     1.0   2000.000000    Ford    Focus
930  H419XE197RUS     2.0   8594.586466  Toyota  Corolla

[725 rows x 5 columns]

In [17]:
df.to_json('../data/auto.json', orient="records")

In [18]:
df2 = pd.read_json('../data/auto.json', orient='records')

In [19]:
df2.count()

CarNumber    725
Refund       725
Fines        725
Make         725
Model        716
dtype: int64

In [20]:
df2.Fines.mean()

8594.586466165412

In [21]:
df.Refund.mean()

1.5172413793103448