In [1]:
import pandas as pd

## create a dataframe views

In [2]:
views = pd.read_csv('../data/feed-views.log', sep='\t', names=['datetime', 'user'], parse_dates=['datetime'])
views.head()

                    datetime   user
0 2020-04-17 12:01:08.463179  artem
1 2020-04-17 12:01:23.743946  artem
2 2020-04-17 12:27:30.646665  artem
3 2020-04-17 12:35:44.884757  artem
4 2020-04-17 12:35:52.735016  artem

In [3]:
views['year'] = views['datetime'].dt.year
views['month'] = views['datetime'].dt.month
views['day'] = views['datetime'].dt.day
views['hour'] = views['datetime'].dt.hour
views['minute'] = views['datetime'].dt.minute
views['second'] = views['datetime'].dt.second

views.head(10)

                    datetime    user  year  month  day  hour  minute  second
0 2020-04-17 12:01:08.463179   artem  2020      4   17    12       1       8
1 2020-04-17 12:01:23.743946   artem  2020      4   17    12       1      23
2 2020-04-17 12:27:30.646665   artem  2020      4   17    12      27      30
3 2020-04-17 12:35:44.884757   artem  2020      4   17    12      35      44
4 2020-04-17 12:35:52.735016   artem  2020      4   17    12      35      52
5 2020-04-17 12:36:21.401412  oksana  2020      4   17    12      36      21
6 2020-04-17 12:36:22.023355  oksana  2020      4   17    12      36      22
7 2020-04-17 13:55:19.129243   artem  2020      4   17    13      55      19
8 2020-04-17 15:00:33.138530   artem  2020      4   17    15       0      33
9 2020-04-17 15:14:09.581054   artem  2020      4   17    15      14       9

## create the new column daytime

In [4]:
bins = [0, 4, 7, 11, 17, 20, 24]
lab = ['night', 'early morning', 'morning', 'afternoon', 'early evening', 'evening']

views['daytime'] = pd.cut(views['hour'], bins = bins, labels=lab, include_lowest=True, right=False)
views.set_index('user', inplace=True)

views.head(10)

,datetime,year,month,day,hour,minute,second,daytime
user,,,,,,,,
artem,2020-04-17 12:01:08.463179,2020,4,17,12,1,8,afternoon
artem,2020-04-17 12:01:23.743946,2020,4,17,12,1,23,afternoon
artem,2020-04-17 12:27:30.646665,2020,4,17,12,27,30,afternoon
artem,2020-04-17 12:35:44.884757,2020,4,17,12,35,44,afternoon
artem,2020-04-17 12:35:52.735016,2020,4,17,12,35,52,afternoon
oksana,2020-04-17 12:36:21.401412,2020,4,17,12,36,21,afternoon
oksana,2020-04-17 12:36:22.023355,2020,4,17,12,36,22,afternoon
artem,2020-04-17 13:55:19.129243,2020,4,17,13,55,19,afternoon
artem,2020-04-17 15:00:33.138530,2020,4,17,15,0,33,afternoon
artem,2020-04-17 15:14:09.581054,2020,4,17,15,14,9,afternoon

## calculate the number of elements in your dataframe

In [5]:
views.count()

datetime    1076
year        1076
month       1076
day         1076
hour        1076
minute      1076
second      1076
daytime     1076
dtype: int64

In [6]:
views.value_counts('daytime')

daytime
evening          509
afternoon        252
early evening    145
night            129
morning           36
early morning      5
Name: count, dtype: int64

## sort values in dataframe by hour, minute and second

In [7]:
views.sort_values(['hour', 'minute', 'second'], inplace=True)
views.head(10)

,datetime,year,month,day,hour,minute,second,daytime
user,,,,,,,,
valentina,2020-05-15 00:00:13.222265,2020,5,15,0,0,13,night
valentina,2020-05-15 00:01:05.153738,2020,5,15,0,1,5,night
pavel,2020-05-12 00:01:27.764025,2020,5,12,0,1,27,night
pavel,2020-05-12 00:01:38.444917,2020,5,12,0,1,38,night
pavel,2020-05-12 00:01:55.395042,2020,5,12,0,1,55,night
valentina,2020-05-15 00:02:05.652585,2020,5,15,0,2,5,night
alexander,2020-05-15 00:05:27.798227,2020,5,15,0,5,27,night
artem,2020-04-20 00:08:17.652510,2020,4,20,0,8,17,night
alexander,2020-05-15 00:10:24.935904,2020,5,15,0,10,24,night
maxim,2020-05-15 00:12:22.886082,2020,5,15,0,12,22,night

## calculate the minimum and maximum for the hours and the mode for the daytime categories

In [8]:
views[views['daytime'] == 'night']['hour'].max()

3

In [9]:
views[views['daytime'] == 'morning']['hour'].min()

8

In [10]:
views.loc[views['daytime'] == 'night'].hour.idxmax()

'konstantin'

In [11]:
views.loc[views['daytime'] == 'morning'].hour.idxmin()

'alexander'

In [12]:
views.hour.mode()

0    22
Name: hour, dtype: int32

In [13]:
views.daytime.mode()

0    evening
Name: daytime, dtype: category
Categories (6, object): ['night' < 'early morning' < 'morning' < 'afternoon' < 'early evening' < 'evening']

## show the 3 earliest hours in the morning and the corresponding usernames and the 3 latest hourst and the usernaes

In [14]:
views[views['daytime'] == 'morning'].nsmallest(3, 'hour').hour

user
alexander    8
alexander    8
alexander    9
Name: hour, dtype: int32

In [15]:
views[views['daytime'] == 'morning'].nlargest(3, 'hour').hour

user
konstantin    10
maxim         10
maxim         10
Name: hour, dtype: int32

## use the method describe() to get the basic statistics for the columns

In [16]:
views.describe()

,datetime,year,month,day,hour,minute,second
count,1076,1076.0,1076.000000,1076.000000,1076.000000,1076.000000,1076.000000
mean,2020-05-10 09:00:41.211420672,2020.0,4.870818,13.552974,16.249071,29.629182,29.500929
min,2020-04-17 12:01:08.463179,2020.0,4.000000,1.000000,0.000000,0.000000,0.000000
25%,2020-05-10 01:13:49.857472,2020.0,5.000000,11.000000,13.000000,14.000000,14.000000
50%,2020-05-11 22:48:35.302552832,2020.0,5.000000,13.000000,19.000000,29.000000,30.000000
75%,2020-05-14 14:44:34.749530624,2020.0,5.000000,15.000000,22.000000,46.000000,45.000000
max,2020-05-22 10:36:14.662600,2020.0,5.000000,30.000000,23.000000,59.000000,59.000000
std,NaN,0.0,0.335557,4.906567,6.955490,17.689388,17.405506

In [17]:
describe_hour = views.hour.describe()
iqr = describe_hour['75%'] - describe_hour['25%']
iqr

9.0

In [18]:
views.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1076 entries, valentina to alexander
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   datetime  1076 non-null   datetime64[ns]
 1   year      1076 non-null   int32
 2   month     1076 non-null   int32
 3   day       1076 non-null   int32
 4   hour      1076 non-null   int32
 5   minute    1076 non-null   int32
 6   second    1076 non-null   int32
 7   daytime   1076 non-null   category
dtypes: category(1), datetime64[ns](1), int32(6)
memory usage: 75.6+ KB

In [19]:
views.count()

datetime    1076
year        1076
month       1076
day         1076
hour        1076
minute      1076
second      1076
daytime     1076
dtype: int64

In [20]:
views.daytime.value_counts()

daytime
evening          509
afternoon        252
early evening    145
night            129
morning           36
early morning      5
Name: count, dtype: int64

In [21]:
views.loc[views.daytime == 'night'].hour.idxmax()

'konstantin'

In [22]:
views.loc[views.daytime == 'morning'].hour.idxmin()

'alexander'

In [23]:
views.hour.mode()

0    22
Name: hour, dtype: int32

In [24]:
views.daytime.mode()

0    evening
Name: daytime, dtype: category
Categories (6, object): ['night' < 'early morning' < 'morning' < 'afternoon' < 'early evening' < 'evening']

In [25]:
iqr

9.0