In [1]:
import pandas as pd
import numpy as np
import requests

## read the JSON file that was saved in ex02

In [2]:
df = pd.read_json('../data/auto.json',orient='records')

In [3]:
pd.options.display.float_format = '{:.2f}'.format

In [4]:
df.head()

      CarNumber  Refund   Fines    Make  Model
0  Y163O8161RUS       2 3200.00    Ford  Focus
1   E432XX77RUS       1 6500.00  Toyota  Camry
2   7184TT36RUS       1 2100.00    Ford  Focus
3  X582HE161RUS       2 2000.00    Ford  Focus
4  92918M178RUS       1 5700.00    Ford  Focus

## enrich the dataframe using a sample from that dataframe

In [5]:
sample_of_combinations = df.sample(n=200, random_state=21)[['CarNumber', 'Make', 'Model']]
sample_of_combinations

        CarNumber        Make   Model
445  M0299X197RUS        Ford   Focus
22   83298C154RUS        Ford   Focus
93   H957HY161RUS        Ford   Focus
173   T941CC96RUS        Ford   Focus
697  H966HY161RUS        Ford   Focus
..            ...         ...     ...
14   8182XX154RUS        Ford   Focus
623   X796TH96RUS        Ford   Focus
498  T011MY163RUS        Ford   Focus
536   T341CC96RUS  Volkswagen  Passat
520   T119CT96RUS        Ford   Focus

[200 rows x 3 columns]

In [6]:
np.random.randint(0, 725)

87

In [7]:
random_samples = pd.DataFrame({
    'CarNumber' : sample_of_combinations.CarNumber.values, 
    'Refund' : [df.Refund.values[np.random.randint(0, 725)] for _ in range(200)],
    'Fines' : [df.Fines.values[np.random.randint(0, 725)] for _ in range(200)],
    'Make' : sample_of_combinations.Make.values,
    'Model' : sample_of_combinations.Model.values
})

random_samples

        CarNumber  Refund    Fines        Make   Model
0    M0299X197RUS       1  8594.59        Ford   Focus
1    83298C154RUS       1  6500.00        Ford   Focus
2    H957HY161RUS       1 10400.00        Ford   Focus
3     T941CC96RUS       1  6200.00        Ford   Focus
4    H966HY161RUS       1 49200.00        Ford   Focus
..            ...     ...      ...         ...     ...
195  8182XX154RUS       1   500.00        Ford   Focus
196   X796TH96RUS       1  1200.00        Ford   Focus
197  T011MY163RUS       1 12300.00        Ford   Focus
198   T341CC96RUS       1  3000.00  Volkswagen  Passat
199   T119CT96RUS       2  3300.00        Ford   Focus

[200 rows x 5 columns]

In [8]:
concat_rows = pd.concat([df, random_samples], ignore_index=True)
concat_rows.count()

CarNumber    925
Refund       925
Fines        925
Make         925
Model        914
dtype: int64

## enrich the dataframe concat_rows by a new column with the data generated

In [9]:
np.random.seed(21)
Year = pd.Series(np.random.randint(1980,2019, size=925))

In [10]:
fines = pd.concat([concat_rows, Year], axis=1)

In [11]:
fines.rename(columns={0 : 'Year'}, inplace=True)

In [12]:
fines.count()

CarNumber    925
Refund       925
Fines        925
Make         925
Model        914
Year         925
dtype: int64

## enrich the dataframe with the data from another dataframe

In [13]:
surnames = pd.read_json('../data/surname.json')
surnames = pd.Series(surnames[0].values[1:])
surnames

0        ADAMS
1        ALLEN
2      ALVAREZ
3     ANDERSON
4       BAILEY
        ...
95    WILLIAMS
96      WILSON
97        WOOD
98      WRIGHT
99       YOUNG
Length: 100, dtype: object

In [14]:
len(fines.CarNumber.unique())

531

In [15]:
surnames = surnames.sample(n=531, random_state=21, replace=True)
surnames

73    RICHARDSON
79          ROSS
56        MORGAN
4         BAILEY
48         LOPEZ
         ...
9       CAMPBELL
31          HALL
5          BAKER
20          DIAZ
56        MORGAN
Length: 531, dtype: object

In [16]:
owners = pd.DataFrame({
    'CarNumber' : fines.CarNumber.unique(),
    'SURNAME' : surnames.values
})
owners

        CarNumber     SURNAME
0    Y163O8161RUS  RICHARDSON
1     E432XX77RUS        ROSS
2     7184TT36RUS      MORGAN
3    X582HE161RUS      BAILEY
4    92918M178RUS       LOPEZ
..            ...         ...
526  O136HO197RUS    CAMPBELL
527  O22097197RUS        HALL
528  M0309X197RUS       BAKER
529  O673E8197RUS        DIAZ
530  8610T8154RUS      MORGAN

[531 rows x 2 columns]

In [17]:
new_observations = pd.DataFrame([{'CarNumber' : 'A228MP68RUS', 'Refund' : 1, 'Fines' :  2800.0, 'Make' : 'Toyota', 'Model' : 'Corolla', 'Year' : 2001},
                    {'CarNumber' : '654X84S6RUS', 'Refund' : 1, 'Fines' :  5600.0, 'Make' : 'Toyota', 'Model' : 'Camry', 'Year' : 1998},
                    {'CarNumber' : '321A56S8RUS', 'Refund' : 1, 'Fines' :  6200.0, 'Make' : 'Ford', 'Model' : 'Focus', 'Year' : 1985},
                    {'CarNumber' : '68SD96A3RUS', 'Refund' : 1, 'Fines' :  1200.0, 'Make' : 'Scoda', 'Model' : 'Octavia', 'Year' : 2013},
                    {'CarNumber' : '226S996DRUS', 'Refund' : 1, 'Fines' :  9800.0, 'Make' : 'Audi', 'Model' : 'Q8', 'Year' : 2005}])
fines = pd.concat([fines, new_observations], ignore_index=True)

In [18]:
fines

        CarNumber  Refund   Fines    Make    Model  Year
0    Y163O8161RUS       2 3200.00    Ford    Focus  1989
1     E432XX77RUS       1 6500.00  Toyota    Camry  1995
2     7184TT36RUS       1 2100.00    Ford    Focus  1984
3    X582HE161RUS       2 2000.00    Ford    Focus  2015
4    92918M178RUS       1 5700.00    Ford    Focus  2014
..            ...     ...     ...     ...      ...   ...
925   A228MP68RUS       1 2800.00  Toyota  Corolla  2001
926   654X84S6RUS       1 5600.00  Toyota    Camry  1998
927   321A56S8RUS       1 6200.00    Ford    Focus  1985
928   68SD96A3RUS       1 1200.00   Scoda  Octavia  2013
929   226S996DRUS       1 9800.00    Audi       Q8  2005

[930 rows x 6 columns]

In [19]:
owners.drop(index=range(511, 531), inplace=True)

In [20]:
new_owners_observations = pd.DataFrame([{'CarNumber' : '987A5668RUS', 'SURNAME' : 'MIKE'},
                                        {'CarNumber' : '987A65S6RUS', 'SURNAME' : 'JAMES'},
                                        {'CarNumber' : '26548465RUS', 'SURNAME' : 'ANTONY'}])
owners = pd.concat([owners, new_owners_observations], ignore_index=True)

In [21]:
owners

        CarNumber     SURNAME
0    Y163O8161RUS  RICHARDSON
1     E432XX77RUS        ROSS
2     7184TT36RUS      MORGAN
3    X582HE161RUS      BAILEY
4    92918M178RUS       LOPEZ
..            ...         ...
509  O50197197RUS      WRIGHT
510  7608EE777RUS        HILL
511   987A5668RUS        MIKE
512   987A65S6RUS       JAMES
513   26548465RUS      ANTONY

[514 rows x 2 columns]

differen ways of join both dataframes

In [22]:
first_merge = fines.merge(owners, how='inner', on='CarNumber')
first_merge

        CarNumber  Refund    Fines        Make   Model  Year     SURNAME
0    Y163O8161RUS       2  3200.00        Ford   Focus  1989  RICHARDSON
1     E432XX77RUS       1  6500.00      Toyota   Camry  1995        ROSS
2     7184TT36RUS       1  2100.00        Ford   Focus  1984      MORGAN
3    X582HE161RUS       2  2000.00        Ford   Focus  2015      BAILEY
4    92918M178RUS       1  5700.00        Ford   Focus  2014       LOPEZ
..            ...     ...      ...         ...     ...   ...         ...
894  8182XX154RUS       1   500.00        Ford   Focus  1996       SMITH
895   X796TH96RUS       1  1200.00        Ford   Focus  2002      WATSON
896  T011MY163RUS       1 12300.00        Ford   Focus  1996     SANDERS
897   T341CC96RUS       1  3000.00  Volkswagen  Passat  2012       PEREZ
898   T119CT96RUS       2  3300.00        Ford   Focus  1984        RUIZ

[899 rows x 7 columns]

In [23]:
second_merge = fines.merge(owners, on='CarNumber', how='outer')
second_merge

        CarNumber  Refund    Fines    Make    Model    Year SURNAME
0     226S996DRUS    1.00  9800.00    Audi       Q8 2005.00     NaN
1     26548465RUS     NaN      NaN     NaN      NaN     NaN  ANTONY
2     321A56S8RUS    1.00  6200.00    Ford    Focus 1985.00     NaN
3     654X84S6RUS    1.00  5600.00  Toyota    Camry 1998.00     NaN
4     68SD96A3RUS    1.00  1200.00   Scoda  Octavia 2013.00     NaN
..            ...     ...      ...     ...      ...     ...     ...
928  Y973O8197RUS    2.00  8594.59    Ford    Focus 2005.00   YOUNG
929  Y973O8197RUS    1.00 34800.00    Ford    Focus 2013.00   YOUNG
930  Y973O8197RUS    1.00 69600.00    Ford    Focus 1989.00   YOUNG
931  Y973O8197RUS    2.00 18800.00    Ford    Focus 2009.00   YOUNG
932  Y973O8197RUS    2.00  7000.00    Ford    Focus 2014.00   YOUNG

[933 rows x 7 columns]

In [24]:
third_merge = fines.merge(owners, on='CarNumber', how='left')
third_merge

        CarNumber  Refund   Fines    Make    Model  Year     SURNAME
0    Y163O8161RUS       2 3200.00    Ford    Focus  1989  RICHARDSON
1     E432XX77RUS       1 6500.00  Toyota    Camry  1995        ROSS
2     7184TT36RUS       1 2100.00    Ford    Focus  1984      MORGAN
3    X582HE161RUS       2 2000.00    Ford    Focus  2015      BAILEY
4    92918M178RUS       1 5700.00    Ford    Focus  2014       LOPEZ
..            ...     ...     ...     ...      ...   ...         ...
925   A228MP68RUS       1 2800.00  Toyota  Corolla  2001         NaN
926   654X84S6RUS       1 5600.00  Toyota    Camry  1998         NaN
927   321A56S8RUS       1 6200.00    Ford    Focus  1985         NaN
928   68SD96A3RUS       1 1200.00   Scoda  Octavia  2013         NaN
929   226S996DRUS       1 9800.00    Audi       Q8  2005         NaN

[930 rows x 7 columns]

In [25]:
fourth_merge = fines.merge(owners, on='CarNumber', how='right')
fourth_merge

        CarNumber  Refund    Fines    Make    Model    Year     SURNAME
0    Y163O8161RUS    2.00  3200.00    Ford    Focus 1989.00  RICHARDSON
1    Y163O8161RUS    2.00  1600.00    Ford    Focus 1999.00  RICHARDSON
2     E432XX77RUS    1.00  6500.00  Toyota    Camry 1995.00        ROSS
3     E432XX77RUS    2.00 13000.00  Toyota    Camry 1992.00        ROSS
4     7184TT36RUS    1.00  2100.00    Ford    Focus 1984.00      MORGAN
..            ...     ...      ...     ...      ...     ...         ...
897  7608EE777RUS    1.00  4000.00   Skoda  Octavia 2013.00        HILL
898  7608EE777RUS    1.00 34400.00   Skoda  Octavia 1987.00        HILL
899   987A5668RUS     NaN      NaN     NaN      NaN     NaN        MIKE
900   987A65S6RUS     NaN      NaN     NaN      NaN     NaN       JAMES
901   26548465RUS     NaN      NaN     NaN      NaN     NaN      ANTONY

[902 rows x 7 columns]

## create a pivot table from the fines dataframe

In [26]:
pd.pivot_table(fines, values='Fines', index=['Make', 'Model'], columns='Year', aggfunc='sum')

Year                   1980      1981     1982      1983      1984      1985  \
Make       Model
Audi       Q8           NaN       NaN      NaN       NaN       NaN       NaN
Ford       Focus   85794.59 325794.59 99300.00 133794.59 101500.00 263294.59
           Mondeo       NaN       NaN 46200.00       NaN       NaN       NaN
Scoda      Octavia      NaN       NaN      NaN       NaN       NaN       NaN
Skoda      Octavia 10194.59   1900.00  8894.59       NaN    400.00  15394.59
Toyota     Camry   12000.00       NaN   500.00    100.00   1000.00       NaN
           Corolla      NaN   6800.00      NaN  12800.00       NaN   1600.00
Volkswagen Golf    20800.00   8594.59  5000.00    200.00       NaN 168000.00
           Jetta        NaN   1000.00      NaN       NaN       NaN   9000.00
           Passat    900.00  66300.00      NaN   1100.00   8594.59       NaN
           Touareg      NaN       NaN      NaN       NaN       NaN       NaN

Year                   1986      1987     1988      1989  ...      2009  \
Make       Model                                          ...
Audi       Q8           NaN       NaN      NaN       NaN  ...       NaN
Ford       Focus   59700.00 141694.59 52478.35 176389.17  ... 138989.17
           Mondeo       NaN       NaN      NaN       NaN  ...       NaN
Scoda      Octavia      NaN       NaN      NaN       NaN  ...       NaN
Skoda      Octavia      NaN  36400.00  5100.00   8594.59  ...       NaN
Toyota     Camry   19800.00       NaN      NaN    800.00  ...       NaN
           Corolla      NaN  54300.00      NaN   7800.00  ...   8594.59
Volkswagen Golf         NaN   1200.00      NaN    300.00  ...       NaN
           Jetta        NaN       NaN 46000.00    800.00  ...       NaN
           Passat  16000.00   2000.00  8594.59       NaN  ...   3000.00
           Touareg      NaN       NaN      NaN       NaN  ...   5800.00

Year                    2010      2011      2012      2013     2014      2015  \
Make       Model
Audi       Q8            NaN       NaN       NaN       NaN      NaN       NaN
Ford       Focus   121200.00 111694.59 134189.17 413483.76 79783.76 185000.00
           Mondeo        NaN       NaN       NaN  41100.00      NaN       NaN
Scoda      Octavia       NaN       NaN       NaN   1200.00      NaN       NaN
Skoda      Octavia   3500.00   3000.00   1700.00  11800.00   300.00  16394.59
Toyota     Camry    22400.00       NaN   7500.00       NaN      NaN       NaN
           Corolla   6000.00   1000.00       NaN       NaN      NaN   8594.59
Volkswagen Golf          NaN       NaN       NaN       NaN 13900.00   4900.00
           Jetta         NaN       NaN       NaN       NaN      NaN       NaN
           Passat    9500.00       NaN   3000.00   1600.00 39600.00       NaN
           Touareg       NaN       NaN       NaN       NaN      NaN       NaN

Year                    2016      2017      2018
Make       Model
Audi       Q8            NaN       NaN       NaN
Ford       Focus   114889.17 102600.00  82900.00
           Mondeo        NaN   8600.00       NaN
Scoda      Octavia       NaN       NaN       NaN
Skoda      Octavia  35700.00   2400.00 153200.00
Toyota     Camry     2500.00       NaN       NaN
           Corolla       NaN    500.00       NaN
Volkswagen Golf          NaN       NaN   6000.00
           Jetta         NaN       NaN       NaN
           Passat        NaN       NaN       NaN
           Touareg       NaN       NaN       NaN

[11 rows x 39 columns]

## save both the fines and owners

In [27]:
fines.to_csv('../data/fines.csv', index=False)

In [28]:
owners.to_csv('../data/owners.csv', index=False)

In [29]:
concat_rows.count()

CarNumber    925
Refund       925
Fines        925
Make         925
Model        914
dtype: int64

In [30]:
fines.count()

CarNumber    930
Refund       930
Fines        930
Make         930
Model        919
Year         930
dtype: int64

In [31]:
len(owners)

514

In [32]:
len(fines)

930