# 1. Download data from Don'tGetKicked competiton.

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.compose import make_column_selector, ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from category_encoders import CountEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import roc_auc_score, make_scorer
from sklearn.pipeline import Pipeline
from tqdm import tqdm
from sklearn.model_selection import GridSearchCV

In [2]:
df = pd.read_csv('./data/training.csv', parse_dates=['PurchDate'])

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72983 entries, 0 to 72982
Data columns (total 34 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   RefId                              72983 non-null  int64
 1   IsBadBuy                           72983 non-null  int64
 2   PurchDate                          72983 non-null  datetime64[ns]
 3   Auction                            72983 non-null  object
 4   VehYear                            72983 non-null  int64
 5   VehicleAge                         72983 non-null  int64
 6   Make                               72983 non-null  object
 7   Model                              72983 non-null  object
 8   Trim                               70623 non-null  object
 9   SubModel                           72975 non-null  object
 10  Color                              72975 non-null  object
 11  Transmission                       72974 non-null  object
 12  WheelTypeID                        69814 non-null  float64
 13  WheelType                          69809 non-null  object
 14  VehOdo                             72983 non-null  int64
 15  Nationality                        72978 non-null  object
 16  Size                               72978 non-null  object
 17  TopThreeAmericanName               72978 non-null  object
 18  MMRAcquisitionAuctionAveragePrice  72965 non-null  float64
 19  MMRAcquisitionAuctionCleanPrice    72965 non-null  float64
 20  MMRAcquisitionRetailAveragePrice   72965 non-null  float64
 21  MMRAcquisitonRetailCleanPrice      72965 non-null  float64
 22  MMRCurrentAuctionAveragePrice      72668 non-null  float64
 23  MMRCurrentAuctionCleanPrice        72668 non-null  float64
 24  MMRCurrentRetailAveragePrice       72668 non-null  float64
 25  MMRCurrentRetailCleanPrice         72668 non-null  float64
 26  PRIMEUNIT                          3419 non-null   object
 27  AUCGUART                           3419 non-null   object
 28  BYRNO                              72983 non-null  int64
 29  VNZIP1                             72983 non-null  int64
 30  VNST                               72983 non-null  object
 31  VehBCost                           72983 non-null  float64
 32  IsOnlineSale                       72983 non-null  int64
 33  WarrantyCost                       72983 non-null  int64
dtypes: datetime64[ns](1), float64(10), int64(9), object(14)
memory usage: 18.9+ MB

# 2. Design the train/validation/test split.

In [4]:
df = df.sort_values('PurchDate')
df.head()

,RefId,IsBadBuy,PurchDate,Auction,VehYear,VehicleAge,Make,Model,Trim,SubModel,...,MMRCurrentRetailAveragePrice,MMRCurrentRetailCleanPrice,PRIMEUNIT,AUCGUART,BYRNO,VNZIP1,VNST,VehBCost,IsOnlineSale,WarrantyCost
32367,32389,0,2009-01-05,MANHEIM,2007,2,CHRYSLER,PACIFICA FWD 3.8L V6,Bas,4D SPORT,...,9906.0,11657.0,NaN,NaN,3453,80022,CO,6770.0,0,1389
32384,32406,0,2009-01-05,MANHEIM,2005,4,FORD,FREESTAR FWD V6 3.9L,SES,4D PASSENGER 3.9L SES,...,5801.0,6949.0,NaN,NaN,22916,80022,CO,6160.0,0,941
32385,32407,0,2009-01-05,MANHEIM,2004,5,DODGE,STRATUS 4C 2.4L I4 M,SE,4D SEDAN SE,...,4169.0,5114.0,NaN,NaN,3453,80022,CO,4250.0,0,1155
32386,32408,0,2009-01-05,MANHEIM,2006,3,CHEVROLET,TRAILBLAZER EXT 4WD,LS,4D SUV 4.2L,...,10438.0,12158.0,NaN,NaN,22916,80022,CO,8180.0,0,1703
32387,32409,0,2009-01-05,MANHEIM,2004,5,FORD,TAURUS 3.0L V6 EFI,SES,4D SEDAN SES DURATEC,...,4139.0,5351.0,NaN,NaN,22916,80022,CO,4900.0,0,825

In [5]:
train_valid_df, test_df = train_test_split(df, test_size=0.33333, shuffle=False)
train_df, valid_df = train_test_split(train_valid_df, test_size=0.5, shuffle=False)

In [6]:
print(len(train_df))
print(len(valid_df))
print(len(test_df))

24327
24328
24328

In [7]:
X_train = train_df.drop(columns=['IsBadBuy', 'PurchDate'])
y_train = train_df['IsBadBuy']

X_valid = valid_df.drop(columns=['IsBadBuy', 'PurchDate'])
y_valid = valid_df['IsBadBuy']

X_test = test_df.drop(columns=['IsBadBuy', 'PurchDate'])
y_test = test_df['IsBadBuy']

# 3. Use LabelEncoder or OneHotEncoder from sklearn to preprocess categorical variables.

In [8]:
train_df.columns

Index(['RefId', 'IsBadBuy', 'PurchDate', 'Auction', 'VehYear', 'VehicleAge',
       'Make', 'Model', 'Trim', 'SubModel', 'Color', 'Transmission',
       'WheelTypeID', 'WheelType', 'VehOdo', 'Nationality', 'Size',
       'TopThreeAmericanName', 'MMRAcquisitionAuctionAveragePrice',
       'MMRAcquisitionAuctionCleanPrice', 'MMRAcquisitionRetailAveragePrice',
       'MMRAcquisitonRetailCleanPrice', 'MMRCurrentAuctionAveragePrice',
       'MMRCurrentAuctionCleanPrice', 'MMRCurrentRetailAveragePrice',
       'MMRCurrentRetailCleanPrice', 'PRIMEUNIT', 'AUCGUART', 'BYRNO',
       'VNZIP1', 'VNST', 'VehBCost', 'IsOnlineSale', 'WarrantyCost'],
      dtype='object')

In [9]:
train_df.IsBadBuy.unique()

array([0, 1])

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 72983 entries, 32367 to 70421
Data columns (total 34 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   RefId                              72983 non-null  int64
 1   IsBadBuy                           72983 non-null  int64
 2   PurchDate                          72983 non-null  datetime64[ns]
 3   Auction                            72983 non-null  object
 4   VehYear                            72983 non-null  int64
 5   VehicleAge                         72983 non-null  int64
 6   Make                               72983 non-null  object
 7   Model                              72983 non-null  object
 8   Trim                               70623 non-null  object
 9   SubModel                           72975 non-null  object
 10  Color                              72975 non-null  object
 11  Transmission                       72974 non-null  object
 12  WheelTypeID                        69814 non-null  float64
 13  WheelType                          69809 non-null  object
 14  VehOdo                             72983 non-null  int64
 15  Nationality                        72978 non-null  object
 16  Size                               72978 non-null  object
 17  TopThreeAmericanName               72978 non-null  object
 18  MMRAcquisitionAuctionAveragePrice  72965 non-null  float64
 19  MMRAcquisitionAuctionCleanPrice    72965 non-null  float64
 20  MMRAcquisitionRetailAveragePrice   72965 non-null  float64
 21  MMRAcquisitonRetailCleanPrice      72965 non-null  float64
 22  MMRCurrentAuctionAveragePrice      72668 non-null  float64
 23  MMRCurrentAuctionCleanPrice        72668 non-null  float64
 24  MMRCurrentRetailAveragePrice       72668 non-null  float64
 25  MMRCurrentRetailCleanPrice         72668 non-null  float64
 26  PRIMEUNIT                          3419 non-null   object
 27  AUCGUART                           3419 non-null   object
 28  BYRNO                              72983 non-null  int64
 29  VNZIP1                             72983 non-null  int64
 30  VNST                               72983 non-null  object
 31  VehBCost                           72983 non-null  float64
 32  IsOnlineSale                       72983 non-null  int64
 33  WarrantyCost                       72983 non-null  int64
dtypes: datetime64[ns](1), float64(10), int64(9), object(14)
memory usage: 19.5+ MB

In [11]:
cat_selector = make_column_selector(dtype_include=['object', 'category'])
cat_columns = cat_selector(train_df)

Список всех столбцов, в которых значения не числовые, а объектные.

In [12]:
cat_columns

['Auction',
 'Make',
 'Model',
 'Trim',
 'SubModel',
 'Color',
 'Transmission',
 'WheelType',
 'Nationality',
 'Size',
 'TopThreeAmericanName',
 'PRIMEUNIT',
 'AUCGUART',
 'VNST']

In [13]:
train_df.VNST.unique()

array(['CO', 'NC', 'CA', 'TX', 'FL', 'UT', 'IN', 'AZ', 'OK', 'SC', 'GA',
       'LA', 'IA', 'VA', 'TN', 'MD', 'MS', 'AL', 'MO', 'OH', 'IL', 'ID',
       'NM', 'PA', 'NV', 'NE', 'NJ', 'KY', 'WA'], dtype=object)

### Анализ каждого признака:
* Auction - поставщик аукциона, на котором было приобретено транспортное стредство. Данные признак будет являться категориальным, так как явного порядко тут задать не получится.
* Make - марка машины. Тоже будет категориальным, хотя и можно было бы попытаться придумать порядок, но будет излишним.
* Model - модель машины. Категорильный признак.
* Trim - уровень отделки салона. Скорее всего уровень указан для разных моделей и марок разный, поэтому порядок установть будет сложно, и может не так критично, как если просто оставить категорилаьными. Хотя если очень глубоко изучить, то можно и составить порядок.
* SubModel - подмодель автомобила. Категорильный признак.
* Color - цвет. Категорильный признак.
* Transmision - коробка передач, то есть автомат или ручная. Можно сказать, что это порядковый, но так как тут всего 2 варианта, то и обычный OneHotEncoder даст то же самое.
* WheeType - тип колёс. Может и можно было бы придумать порядок, но очень сомнительно. Обычный категорильаный признак.
* Natinality - национальнось, или же регион или страна производителя. Категорильный признак.
* Size - скорее имеется ввиду тип кузова, но как бы размер. С одной стороны можно было порядок ввести, однако например тип SPORTS не получится объединить с другими типами, так как это скорее про тип кузова, так что тут тоже категорильный.
* TopThreeAmericanName - определяет, входит ли производитель в топ 3 американских производителей. Категорильный признак.
* PRIMEUNIT - определяет, будет ли спрос на транспортное средство выше, чем при стандартной покупке. Категорильный признак. Хотя тут значения либо YES либо пропещенный, поэтому тут порядка и не получитя придумать. А ещё супер много пропущенных значений, может быть лучше вообще выбросить этот признак. Всех nan на 0 не факт, что поможет, хотя в целом можно и будте оставить, просто где есть ответ, там потавить 1.
* AUCGUART - уровень гарантии, предоставляемой на аукционе. GREEN - значит всё хорошо, остальных вариантов в train нет, и может быть в других частях есть, но не факт, также много пропущенных значений, хотя вот тут как раз и можно было бы применить порядковое.
* VNST - штат, в котором приобрели автомобиль. Категорильный признак.

Теперь надо разобраться с тем, что делать с пропущенными значениями. Стоит ли придумать на что их заменить или убрать те признаки, в которых пропущенно очень много значений.

In [14]:
X_train.isna().sum()[X_train.isna().sum() > 0]

Trim                                   727
SubModel                                 8
Color                                    8
Transmission                             8
WheelTypeID                            925
WheelType                              925
MMRAcquisitionAuctionAveragePrice        3
MMRAcquisitionAuctionCleanPrice          3
MMRAcquisitionRetailAveragePrice         3
MMRAcquisitonRetailCleanPrice            3
MMRCurrentAuctionAveragePrice          260
MMRCurrentAuctionCleanPrice            260
MMRCurrentRetailAveragePrice           260
MMRCurrentRetailCleanPrice             260
PRIMEUNIT                            24325
AUCGUART                             24325
dtype: int64

Сразу стоит сказать , что для признаков PRIMEUNIT и AUCGART пропуссков больше 90% от всей тренировочнйо выборки, при этом предположение о том, что если значение nan, то оно обратное, так как это поля про то, что  будет ли спрос выше и про гарантию, то предполгать обратное может быть ошибочным. Поэтому лучше будет избавиться от этих признак вовсе.

In [15]:
X_train['Trim'].value_counts().iloc[0]

np.int64(4540)

Для поля Trim думаю будет оптимальным вариантом для пропущенных значения установить значеиние Bas, то есть базовые обычные.

In [16]:
X_train['SubModel'].value_counts()

SubModel
4D SEDAN              4903
4D SEDAN SE           1427
4D SEDAN LS           1259
4D SEDAN SXT FFV       742
MINIVAN 3.3L           517
                      ...
PASSENGER 3.4L LS        1
MEGA CAB 5.7L            1
REG CAB 6.0L LS          1
EXT CAB 4.7L             1
PASSENGER EXT 3.9L       1
Name: count, Length: 663, dtype: int64

Для SUbModel, Color, Transmission просто заменю Nan на самые часто встречающиеся значения.

In [17]:
X_train['WheelTypeID'].value_counts()

WheelTypeID
1.0    12545
2.0    10622
3.0      235
Name: count, dtype: int64

Для колес оба поля Nan заменю на самые частво встречющиеся.

Остальные числовые признаки заменю срденими значениями.

In [18]:
X_train.isna().sum()[X_train.isna().sum() > 0].index

Index(['Trim', 'SubModel', 'Color', 'Transmission', 'WheelTypeID', 'WheelType',
       'MMRAcquisitionAuctionAveragePrice', 'MMRAcquisitionAuctionCleanPrice',
       'MMRAcquisitionRetailAveragePrice', 'MMRAcquisitonRetailCleanPrice',
       'MMRCurrentAuctionAveragePrice', 'MMRCurrentAuctionCleanPrice',
       'MMRCurrentRetailAveragePrice', 'MMRCurrentRetailCleanPrice',
       'PRIMEUNIT', 'AUCGUART'],
      dtype='object')

In [19]:
X_train[X_train['Trim'].isna()]

,RefId,Auction,VehYear,VehicleAge,Make,Model,Trim,SubModel,Color,Transmission,...,MMRCurrentRetailAveragePrice,MMRCurrentRetailCleanPrice,PRIMEUNIT,AUCGUART,BYRNO,VNZIP1,VNST,VehBCost,IsOnlineSale,WarrantyCost
8866,8875,MANHEIM,2004,5,KIA,AMANTI 3.5L V6 MPI,NaN,4D SEDAN,BLUE,AUTO,...,5369.0,6421.0,NaN,NaN,17675,27542,NC,5535.0,0,1118
32377,32399,MANHEIM,2004,5,CHRYSLER,PACIFICA AWD 3.5L V6,NaN,4D SPORT TOURER,WHITE,AUTO,...,8311.0,9676.0,NaN,NaN,22916,80022,CO,6010.0,0,2022
33243,33265,MANHEIM,2005,4,SATURN,RELAY 2WD V6 3.5L V6,NaN,4D SPORT UTILITY,BLUE,AUTO,...,6736.0,8247.0,NaN,NaN,5546,34761,FL,5355.0,0,2282
33242,33264,MANHEIM,2002,7,LINCOLN,CONTINENTAL 4.6L V8,NaN,4D SEDAN,SILVER,AUTO,...,4763.0,5743.0,NaN,NaN,21973,34761,FL,5000.0,0,1572
33238,33260,MANHEIM,2007,2,SUZUKI,FORENZA 2.0L I4 EFI,NaN,4D SEDAN,RED,MANUAL,...,6620.0,7376.0,NaN,NaN,19638,34761,FL,4750.0,0,482
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19009,19022,MANHEIM,2004,5,CHRYSLER,PACIFICA AWD 3.5L V6,NaN,4D SPORT TOURER,SILVER,AUTO,...,8087.0,9831.0,NaN,NaN,22916,80022,CO,8380.0,0,2206
19013,19026,MANHEIM,2002,7,LEXUS,ES300 3.0L V6 EFI,NaN,4D SEDAN,SILVER,AUTO,...,9976.0,11511.0,NaN,NaN,22916,80022,CO,10190.0,0,1497
59536,59565,ADESA,2007,2,SUZUKI,FORENZA 2.0L I4 EFI,NaN,4D SEDAN,RED,AUTO,...,6741.0,7695.0,NaN,NaN,18822,78754,TX,5800.0,0,482
13522,13532,MANHEIM,2001,8,LEXUS,GS300 3.0L I6 EFI,NaN,4D SEDAN,SILVER,AUTO,...,9324.0,11159.0,NaN,NaN,16044,21075,MD,8185.0,0,1413
19029,19042,MANHEIM,2006,3,SUZUKI,RENO 2.0L I4 EFI,NaN,4D SEDAN,RED,AUTO,...,6715.0,7808.0,NaN,NaN,22916,80022,CO,5660.0,0,533

In [20]:
def remove_nan_values(X_train, X_valid, X_test):
     # убираем 2 столбца с пропущенными значениями
    X_train.drop(columns=['PRIMEUNIT', 'AUCGUART'], inplace=True)
    X_valid.drop(columns=['PRIMEUNIT', 'AUCGUART'], inplace=True)
    X_test.drop(columns=['PRIMEUNIT', 'AUCGUART'], inplace=True)

    features_top = ['Trim', 'SubModel', 'Color', 'Transmission', 'WheelTypeID', 'WheelType']
    features_mean = ['MMRAcquisitionAuctionAveragePrice', 'MMRAcquisitionAuctionCleanPrice',
       'MMRAcquisitionRetailAveragePrice', 'MMRAcquisitonRetailCleanPrice',
       'MMRCurrentAuctionAveragePrice', 'MMRCurrentAuctionCleanPrice',
       'MMRCurrentRetailAveragePrice', 'MMRCurrentRetailCleanPrice']
    
    for feature in features_top:
        base = X_train[feature].value_counts().iloc[0]

        X_train.loc[X_train[feature].isna(), feature] = base
        X_valid.loc[X_valid[feature].isna(), feature] = base
        X_test.loc[X_test[feature].isna(), feature] = base

    for feature in features_mean:
        base = X_train[feature].mean()

        X_train.loc[X_train[feature].isna(), feature] = base
        X_valid.loc[X_valid[feature].isna(), feature] = base
        X_test.loc[X_test[feature].isna(), feature] = base
    
    return X_train, X_valid, X_test

In [21]:
X_train, X_valid, X_test = remove_nan_values(X_train, X_valid, X_test)

In [22]:
y_valid.drop(index=X_valid[X_valid['Size'].isna()].index, inplace=True)
X_valid.drop(index=X_valid[X_valid['Size'].isna()].index, inplace=True)
X_valid.isna().sum().sum()

np.int64(0)

С пропусками разобрались, теперь применим encoder

In [23]:
categorical_columns = ['Auction', 'Make', 'Model', 'Trim', 'SubModel', 'Color', 'Transmission', 'WheelType', 'Nationality', 'Size', 'TopThreeAmericanName', 'VNST']

In [24]:
for col in categorical_columns:
    X_train[col] = X_train[col].astype(str)
    X_valid[col] = X_valid[col].astype(str)
    X_test[col] = X_test[col].astype(str)

In [25]:
numeric_columns = [column for column in X_train.columns if column not in categorical_columns]
numeric_columns

['RefId',
 'VehYear',
 'VehicleAge',
 'WheelTypeID',
 'VehOdo',
 'MMRAcquisitionAuctionAveragePrice',
 'MMRAcquisitionAuctionCleanPrice',
 'MMRAcquisitionRetailAveragePrice',
 'MMRAcquisitonRetailCleanPrice',
 'MMRCurrentAuctionAveragePrice',
 'MMRCurrentAuctionCleanPrice',
 'MMRCurrentRetailAveragePrice',
 'MMRCurrentRetailCleanPrice',
 'BYRNO',
 'VNZIP1',
 'VehBCost',
 'IsOnlineSale',
 'WarrantyCost']

In [26]:
for col in categorical_columns:
    print(f'\nFor {col}: \n')
    print(X_valid[col].unique())

For Auction:

['MANHEIM' 'OTHER' 'ADESA']

For Make:

['CHRYSLER' 'FORD' 'CHEVROLET' 'SATURN' 'BUICK' 'DODGE' 'MAZDA' 'HYUNDAI'
 'KIA' 'SCION' 'MERCURY' 'PONTIAC' 'JEEP' 'OLDSMOBILE' 'TOYOTA' 'NISSAN'
 'SUZUKI' 'GMC' 'HONDA' 'LINCOLN' 'MITSUBISHI' 'INFINITI' 'LEXUS' 'ACURA'
 'ISUZU' 'VOLKSWAGEN' 'MINI' 'TOYOTA SCION' 'SUBARU' 'CADILLAC' 'VOLVO']

For Model:

['PT CRUISER 2.4L I4 S' 'ESCAPE 4WD V6 3.0L V' 'TOWN & COUNTRY 2WD V'
 '1500 SILVERADO PICKU' 'EXPEDITION 2WD V8 4.' 'VUE 2WD 4C 2.2L I4 M'
 'COBALT 2.2L I4 MPI' 'MALIBU V6 3.5L V6 SF' 'RENDEZVOUS AWD 3.4L'
 '1500 RAM PICKUP 2WD' 'MALIBU 4C 2.2L I4 MP' 'PACIFICA FWD 3.5L V6'
 'NEON 2.0L I4 SFI' 'UPLANDER FWD V6 3.9L' 'STRATUS 4C 2.4L I4 S'
 'DURANGO 2WD V6 3.7L' 'CARAVAN FWD V6 3.3L' 'MAZDA6 2.3L I4 MFI /'
 'MAGNUM V6 2.7L V6 MP' 'F150 PICKUP 2WD V6 4' 'FOCUS 2.3L I4 DOHC'
 'IMPALA 3.5L V6 SFI' 'ELANTRA 2.0L I4 MPI' 'ION 2.0L I4 MPI'
 'AVENGER 4C 2.4L I4 S' 'CAVALIER 4C 2.2L I4' 'SORENTO 4WD 3.5L V6'
 'TIBURON MFI I-4 2.0L' 'TC 2.4L I-4 EFI DOHC' 'MOUNTAINEER 2WD V6 4'
 'IMPALA 3.8L V6 MFI' 'HHR 2.2L I4 MPI' 'TOWN & COUNTRY FWD V'
 'MONTE CARLO 3.5L V6' 'MAGNUM V8 5.7L V8 SF' 'STRATUS 4C 2.4L I4 M'
 'TAURUS 3.0L V6 EFI' 'AVALANCHE 1500 4WD V' 'CARAVAN GRAND FWD V6'
 'FOCUS 2.3L I4 SFI' 'FIVE HUNDRED 3.0L V6' 'TAURUS 3.0L V6 EFI F'
 'WINDSTAR FWD V6 3.8L' 'F150 PICKUP 2WD V8 4' 'SEBRING V6 2.7L V6 M'
 'TRAILBLAZER 2WD 6C 4' 'SPECTRA 2.0L I4 EFI' 'TERRAZA FWD V6 3.5L'
 'GRAND PRIX 3.8L V6 S' 'GRAND CHEROKEE 2WD V' 'IMPALA 3.4L V6 SFI'
 'SEBRING 4C 2.4L I4 S' 'ALERO 4C 2.2L I4 MPI' 'EQUINOX FWD V6 3.4L'
 'DAKOTA PICKUP 2WD V8' 'SEBRING 4C 2.4L I4 E' 'TAURUS 3.0L V6 EFI S'
 'DURANGO 2WD V8 4.7L' 'MALIBU MAXX V6 3.5L' 'MAGNUM V6 3.5L V6 MP'
 'CHARGER V6 2.7L V6 M' 'MUSTANG V6 3.8L V6 E' 'ION 2.2L I4 EFI'
 'FREESTYLE FWD V6 3.0' 'RONDO 4C 2.4L I4 MPI' 'LE SABRE Unspecified'
 'MALIBU V6 3.1L V6 SF' 'CAMRY 4C 2.4L I4 SFI' 'GRAND CHEROKEE 2WD 6'
 'FREESTAR FWD V6 3.9L' 'CARAVAN FWD 4C 2.4L' 'SABLE 3.0L V6 4V /EF'
 'MAXIMA 3.5L V6 MPI' 'RANGER PICKUP 2WD 4C' 'PACIFICA AWD 4.0L V6'
 'FORENZA 2.0L I4 EFI' 'CANYON PICKUP 2WD I5' 'SENTRA 1.8L I4 EFI'
 'ACCORD 4C 2.4L I4 MP' 'AVALANCHE 1500 2WD V' 'EXPEDITION 2WD V8 5.'
 'GRAND PRIX 3.1L V6 S' 'NAVIGATOR 2WD V8 5.4' 'ACCORD V6 3.0L V6 EF'
 'SUBURBAN 1500 2WD 5.' 'ALTIMA 2.5L I4 EFI' 'L SERIES 2.0L I4 MPI'
 'SONATA V6 3.3L V6 MP' 'IMPALA 3.9L V6 SFI' 'EXPEDITION 4WD V8 5.'
 '300 2.7L V6 MPI' 'CAMRY 4C 2.4L I-4 EF' 'G6 V6 3.5L V6 SFI'
 'AVEO 1.6L I4 EFI' 'TRAILBLAZER 4WD 6C 4' 'UPLANDER FWD V6 3.5L'
 'GALANT V6 3.8L V6 MP' 'CALIBER 2.0L I4 SFI' 'PT CRUISER 2.4L I4 M'
 'ALERO V6 3.4L V6 MPI' 'FOCUS 2.0L I4 SFI' 'ELANTRA MFI I-4 2.0L'
 'SUNFIRE 2.2L I4 MPI' 'DURANGO 4WD V8 4.7L' 'LIBERTY 2WD V6 3.7L'
 'RIO 1.6L I4 MPI' 'FUSION 4C 2.3L I4 EF' 'G35 3.5L V6 MPI'
 'LIBERTY 4WD V6 3.7L' 'STRATUS V6 2.7L V6 M' 'COMPASS 2WD 4C 2.4L'
 'GALANT 4C 2.4L I4 EF' 'EXPLORER 2WD V6 4.0L' 'TAHOE 2WD 5.3L V8 SF'
 'NEON 2.0L I-4 SFI SO' 'XG 350 3.5L V6 EFI /' 'DURANGO 2WD V8 5.7L'
 'ES300 3.0L V6 EFI DO' 'MURANO 2WD V6 3.5L V' 'MONTANA 3.4L V6 EFI'
 'TRIBUTE 2WD 4C 2.3L' 'RENDEZVOUS FWD 3.4L' 'YUKON XL 1500 2WD 5.'
 'CAMRY SOLARA 4C 2.4L' 'TAHOE 4WD 4.8L V8 SF' 'CR-V 2WD 2.0L I 4 NA'
 'ALTIMA MFI I-4 2.5L' 'ALTIMA 2.5L I4 MPI' 'SABLE 3.0L V6 EFI'
 'SENTRA 2.5L I-4 EFI' 'SENTRA 1.8L I4 EFI /' 'MALIBU V6 3.5L V6 MF'
 'HHR 2.4L I4 MPI' 'AVEO 1.6L I-4 EFI DO' 'SANTA FE 2WD V6 3.5L'
 'VENTURE FWD V6 3.4L' 'MAGNUM V6' 'ESCAPE 2WD 4C 2.3L I'
 'PACIFICA FWD 4.0L V6' 'SANTA FE 2WD V6 2.7L' '3.2 TL 3.2L V6 EFI'
 'IMPALA V6 3.5L V6 SF' 'GRAND AM V6 3.4L V 6' 'TITAN PICKUP 2WD V8'
 'FUSION V6 3.0L V6 EF' 'CONCORDE 3.5L V6 MPI' 'GRAND AM V6 3.4L V6'
 'NITRO 2WD V6 3.7L V6' 'EXPEDITION 4WD V8 4.' 'XB 1.5L I-4 EFI DOHC'
 'VIBE 1.8L I4 MPI' 'MAZDA6 3.0L V6 MPI D' 'MAXIMA 3.0L V6 EFI D'
 'PT CRUISER 2.4L I-4' 'DURANGO 4WD V8 5.7L' 'L SERIES 3.0L V6 EFI'
 'COMPASS 2WD 4C 2.0L' 'CHARGER V6 3.5L V6 E' 'DAKOTA PICKUP 2WD V6'
 '1500 SIERRA PICKUP 2' 'ION 2.2L I4 EFI / SF' 'TAURUS 3.0L V6 EFI D'
 'XB 1.5L I4 EFI' 'OUTLANDER 2WD 4C 2.4' 'TRAILBLAZER EXT 2WD'
 'ACCENT 1.6L I4 MPI' 'MUSTANG V6 4.0L V6 E' 'ACCORD 4C'
 'OPTIMA V6 2.7L V6 MP' 'S10 PICKUP 2WD V6 4.' 'OPTIMA 4C 2.4L I4 MP'
 '300 3.5L V6 MPI / SM' 'TAHOE 4WD 5.3L V8 SF' 'SPORTAGE 2WD 4C MFI'
 'FRONTIER PICKUP 2WD' 'VOYAGER FWD V6 3.3L' 'RENDEZVOUS AWD 3.5L'
 'LANCER 2.0L I4 MPI' 'SONATA V6 2.7L V6 MP' 'S SERIES 1.9L I4 SFI'
 'PACIFICA AWD 3.5L V6' 'CHARGER 3.5L V6 EFI' 'TUNDRA PICKUP 2WD V8'
 'SABLE 3.0L V6 2V /EF' 'PROTEGE 5 2.0L I-4 M' 'MAZDA6 2.3L I4 MPI'
 'SX4 2.0L I4 EFI' 'FOCUS 2.0L I4 SPI' 'INTREPID 3.5L V6 MPI'
 'GRAND CHEROKEE 4WD V' 'L SERIES 2.2L I4 MPI' 'PACIFICA FWD 3.8L V6'
 'FOCUS 2.0L I4 SFI /' 'GALANT 4C' 'G6 4C 2.4L I4 MPI' 'MAZDA6' 'AVEO'
 'G5 4C 2.2L I4 MPI' 'HHR' 'SONATA 4C 2.4L I4 MP' 'IMPALA 3.8L V6 SFI'
 'LACROSSE 3.8L V6 SFI' 'MONTE CARLO 3.4L V6' '300 3.5L V6 MPI'
 'RX300 2WD 3.0L V6 EF' 'RENO 2.0L I4 EFI' 'TRACKER 4WD V6 2.5L'
 'ENVOY XL 2WD 6C 4.2L' 'L SERIES 2.0L I-4 MP' 'ECLIPSE 2.4L I4 EFI'
 'GRAND PRIX 3.8L V6 M' 'TOWN CAR 4.6L V8 EFI' 'COMMANDER 2WD V6 3.7'
 'TAURUS 3.0L V6 SFI' 'MONTEGO 3.0L V6 EFI' 'FOCUS 2.3L I-4 DOHC'
 'ASCENDER 2WD 6C' 'SORENTO 2WD 3.5L V6' 'MUSTANG V6 3.9L V6 E'
 'GRAND AM 4C 2.2L I4' 'MALIBU 4C 2.4L I4 MP' 'ENVOY 4WD 6C 4.2L I-'
 'ION 2.2L I4 MPI' 'F150 PICKUP 2WD V8 5' 'SUBURBAN 1500 4WD 5.'
 'BEETLE 2.0L I4 EFI' 'S10 PICKUP 2WD V6 MF' 'YARIS 1.5L I4 EFI /'
 'FOCUS 2.0L I-4 SFI D' 'VUE AWD 4C 2.2L I-4' 'MPV 2WD V6 3.0L V6 M'
 'ENVOY XL 4WD V8 5.3L' 'MILAN 4C 2.3L I4 EFI' 'AERIO 2.3L I4 SFI'
 'ALTIMA 2.5L I-4 EFI' 'ENDEAVOR FWD 3.8L V6' 'CHARGER 2.7L V6 MPI'
 'MAZDA3 2.0L I4 MPI' 'ESCAPE 4WD 4C 2.3L I' 'IMPALA 3.5L V6 SFI F'
 'XTERRA 2WD V6 3.3L V' 'YUKON 4WD V8 4.8L V8' 'TRIBUTE 2WD V6 3.0L'
 'DURANGO 4WD V8' 'CHEROKEE 2WD 6C 4.0L' 'IMPALA V6 3.9L V6 SF'
 'ION 2.2L I-4 MPI DOH' 'RENO 2.0L I4 DI / EF' 'ACCENT 1.6L I-4 MPI'
 'ENVOY 2WD 6C 4.2L I6' 'VUE AWD V6 3.5L V6 M' 'FOCUS 2.0L I-4 SFI S'
 'MUSTANG V8 4.6L V8 E' 'YUKON 2WD V8 4.8L V8' 'TRAILBLAZER EXT 4WD'
 'LUCERNE V6 3.8L V6 S' 'HHR 2.2L I4 MPI / SF' 'TRACKER 2WD V6 2.5L'
 'VUE 2WD V6 3.5L V6 M' 'LE SABRE 3.8L V6 MFI' 'BONNEVILLE 3.8L V6 M'
 '2500HD SILVERADO PIC' 'MAZDA6 3.0L V6 MFI /' 'AVIATOR 2WD V8 4.6L'
 'COROLLA 1.8L I-4 EFI' 'MONTE CARLO 3.9L V6' 'EXPLORER 4WD V6 4.0L'
 'SPECTRA 2.0L I-4 EFI' 'SPORTAGE 2WD 4C 2.0L' 'PILOT 3.5L V6 MPI'
 'ALTIMA 3.5L V6 MPI' 'AVEO 1.6L I-4 MPI DO' 'COROLLA 1.8L I4 EFI'
 'OPTIMA V6' 'MAZDA3 2.0L I4 MFI /' 'EQUINOX AWD V6 3.4L'
 'ESCAPE 2WD V6 3.0L V' 'MAZDA5 2.3L I4 MFI /' 'ENVOY 4WD 6C 4.2L I6'
 'AMANTI 3.5L V6 MPI' 'MONTANA AWD 3.5L V6' 'ENVOY XL 4WD 6C 4.2L'
 'CAVALIER 4C 2.2L I-4' 'SEBRING V6 3.0L V6 M' 'SPECTRA 6-230/250-1V'
 'COOPER 1.6L I4 EFI' 'ION 2.2L I4 MPI / SF' 'IMPALA V6 3.5L V6 MP'
 'ECLIPSE 2.4L I4 MPI' 'RANGER PICKUP 2WD V6' 'RENDEZVOUS FWD 3.5L'
 'TRIBUTE 4WD V6 3.0L' 'PT CRUISER 2.4L I4 D' 'S SERIES 1.9L I-4 SF'
 'PATHFINDER 4WD V6 3.' 'ALTIMA 2.5L I4 MPI /' 'ENVOY 2WD 6C 4.2L I-'
 'NITRO 4WD V6 3.7L V6' 'AERIO 2.3L I4 DI / S' 'TAURUS' 'AZERA'
 'AZERA 3.8L V6 MPI' 'OUTLANDER AWD 4C' 'SEBRING V6 MFI V6 2.'
 'YUKON 4WD V8 5.3L V8' 'GRAND AM 4C 2.2L I-4' 'CENTURY V6 3.1L V6 S'
 'HIGHLANDER 4WD V6' 'FOCUS 2.0L I4 EFI' 'YUKON 2WD V8 5.3L V8'
 'LANCER 2.4L I4 MPI' '300M 3.5L V6 MPI HO' 'BONNEVILLE 3.8L V6 S'
 'AVEO 1.6L I4 EFI / M' 'GRAND MARQUIS 4.6L V' 'VIBE 1.8L I4 MFI / M'
 'MONTE CARLO 3.8L V6' 'MARINER 2WD 4C 2.3L' 'FORENZA 2.0L I4 DI /'
 'FOCUS 2.0L I-4 SPI' 'SEDONA 3.8L V6 MPI' 'MALIBU V6'
 'STRATUS 4C 2.4L I-4' 'SUNFIRE 2.2L I-4 MPI' 'XG 300 Unspecified'
 'ACCORD 4C 2.3L I-4 E' 'VUE AWD 4C 2.2L I4 M' 'COUPE 1.9L I-4 SFI S'
 'AURA V6 3.5L V6 SFI' 'FOCUS 2.0L I-4 EFI D' 'SANTA FE 2WD 4C 2.4L'
 'ASCENDER 2WD 6C 4.2L' 'PROTEGE 2.0L I4 EFI' '3.2 CL 3.2L V 6 NA S'
 'MONTERO SPORT 2WD V6' 'M45 4.5L V8 MPI / SF' 'DURANGO 2WD V8 5.9L'
 'FREESTYLE 2WD V6 3.0' 'CIVIC 1.7L I-4 MPI S' 'AERIO 2.3L I-4 SFI D'
 'AURA 3.5L V6 SFI' 'MAZDA3 2.0L I-4 MPI' 'ECHO 1.5L I4 EFI'
 'MAZDA3 2.3L I4 MPI' 'MONTEGO' 'MONTANA FWD 3.5L V6'
 'COLORADO PICKUP 2WD' 'GRAND VITARA 2WD 2.5' 'MONTEREY 4.2L V6 SPI'
 'SONATA V6 MFI V6 2.7' '1500HD SILVERADO PIC' 'EXPLORER 2WD V8 4.6L'
 'SEQUOIA 2WD 4.7L V8' '626 4C 2.0L I-4 EFI' 'CAMRY SOLARA V6 3.0L'
 'RELAY 2WD V6 3.5L V6' 'CAMRY V6 3.5L V6 SFI' 'HHR 2.4L I-4 MPI'
 'PATRIOT 2WD 4C 2.0L' '2500 RAM PICKUP 2WD' 'FREESTAR FWD V6 4.2L'
 'BEETLE 2.0L I4 MPI' 'TAURUS 3.5L V6 24V /' 'CIVIC 1.7L I4 MFI /'
 'GALANT 4C 2.4L I-4 E' 'ACCORD V6' 'S10 PICKUP 2WD 4C 2.'
 'COROLLA Multiple Eng' 'CR-V 4WD 2.0L I-4 MP' 'DURANGO 2WD V8'
 'TAHOE 2WD 4.8L V8 SF' 'CAMRY 4C Multiple En' 'CAMRY 4C 2.4L I4 EFI'
 'STRATUS V6 2.4L I-4' 'GRAND CHEROKEE 4WD 6' 'XTERRA 4WD V6 3.3L V'
 'RONDO V6 2.7L V6 MPI' 'WRANGLER 6C 4.0L I-6' 'RAINIER RWD V6 4.2L'
 'VENTURE AWD V6 3.4L' 'CAVALIER 4C 2.2L I 4' 'CAMRY 4C 2.4L I-4 SF'
 'GX470 4WD' 'HIGHLANDER 2WD 4C 2.' 'ESCORT 2.0L I-4 EFI'
 'ESCORT 2.0L I4 EFI' 'DURANGO 4WD V8 5.9L' 'SANTA FE 4WD V6 2.7L'
 'ALERO 4C 2.2L I-4 MP' 'COMMANDER 4WD V6 3.7' 'SONOMA PICKUP 2WD V6'
 'GRAND VITARA 2WD 2.7' 'MAXIMA MFI V6 3.5L D' 'CAMRY SOLARA 4C Mult'
 'FREESTYLE AWD V6 3.0' 'XA 1.5L I4 EFI' 'TUCSON 2WD V6 2.7L V'
 'IMPALA V6' 'VUE 2WD 4C 2.2L I-4' 'ACCENT 1.5L I-4 EFI'
 'PATHFINDER 2WD V6 MF' 'SUBURBAN 1500 2WD' 'FOCUS' 'MONTANA FWD 3.4L V6'
 'COMMANDER' 'CALIBER 1.8L I4 SFI' 'PT CRUISER' 'MARINER 2WD V6 3.0L'
 'FOCUS 2.0L I4 MFI /' 'SABLE 3.5L V6 24V /' 'GRAND VITARA 2WD'
 'MONTANA AWD' 'SENTRA 2.0L I4 EFI' 'XTERRA 2WD 4C 2.4L I'
 'TAURUS 3.0L V6 EFI /' 'SPORTAGE 2WD V6 2.7L' 'CONCORDE 2.7L V6 SFI'
 'FOCUS 2.3L I4 MFI' 'CX-7 FWD 4C' 'LEGACY' 'CAMRY V6 3.0L V6 SFI'
 'MAZDA6 3.0L V6 MPI' 'SONATA V6' 'ECLIPSE 3.0L V6 EFI' 'UPLANDER FWD V6'
 'SPECTRA 5 2.0L I4 EF' 'AVENGER V6 Unspecifi' 'SEBRING 4C 2.4L I-4'
 'CONTINENTAL 4.6L V8' 'YARIS' 'QUEST 3.5L V6 EFI /'
 'SPORTAGE 2WD 4C 2.7L' 'CIVIC' 'XL-7 4WD 2.7L V6 MPI'
 'ACCORD 4C 2.4L I-4 M' 'F150 PICKUP 4WD V8 4' 'COBALT'
 '1500 RAM PICKUP 4WD' 'BEETLE' 'GRAND AM 4C 2.4L I-4' 'G6 V6'
 'SABLE 3.0L V6 EFI 2B' 'ESCAPE 2WD 4C 2.0L I' 'COOPER S 1.6L I4 EFI'
 'INTREPID 2.7L V6 SFI' 'TRACKER 2WD 4C 2.0L' 'ENVOY XL 4WD V8'
 'MATRIX 2WD 1.8L I-4' 'CROWN VICTORIA 4.6L' 'RAIDER 2WD V6 3.7L V'
 'REGAL 3.8L V6 SFI' 'IS300' 'MARINER 4WD 4C 2.3L' 'TAURUS X FWD V6 3.5L'
 'SABLE 3.0L V6 EFI DO' 'MAXIMA 3.5L V6 MPI /' '300 3.5L / 6.0L V12'
 'XTERRA 2WD V6 4.0L V' 'ALERO V6' 'XL-7 2WD 2.7L V6 MFI'
 'SEBRING V6 2.4L I4 S' 'ION' 'RIO 5' 'F250 PICKUP 2WD V8' 'G6 4C'
 'MPV 2WD V6' 'SONATA 4C MFI I-4 2.' 'LANCER' 'SIENNA 3.0L V6 MPI'
 '4 RUNNER 2WD V8 4.7L' 'MILAN V6 3.0L V6 EFI' 'MONTERO 4WD V6 3.5L'
 'COMMANDER 4WD V8' 'MUSTANG V6 Unspecifi' 'FIVE HUNDRED'
 'B2300 PICKUP 2WD 4C' 'FIREBIRD V6 3.8L V6' 'CX-7 FWD 4C 2.3L I4'
 'ALTIMA' 'SORENTO 2WD 3.8L V6' 'LANCER 2.0L I-4 MPI'
 'NEON 2.0L I4 SFI / S' 'AVENGER V6' 'STRATUS V6 3.0L V6 E'
 'MARINER 4WD V6 3.0L' 'ES300 3.0L V6 EFI' 'RAINIER AWD V6 4.2L'
 'CAVALIER 4C 2.4L I-4' 'CALIBER' 'SEBRING 4C' 'VENTURE AWD V6' 'NEON'
 'SEBRING V6' 'LIBERTY 4WD V6' 'AVENGER 4C' 'L SERIES' 'IMPALA' 'RENO'
 'TRAILBLAZER 4WD 6C' 'ESCAPE 2WD V6' 'SPECTRA' 'TRACKER 4WD V6'
 'OPTIMA 4C' 'PACIFICA FWD' '300' 'ENVOY 2WD 6C' 'GRAND PRIX' 'STRATUS V6'
 'TAHOE 4WD' 'EQUINOX FWD V6' 'WINDSTAR FWD V6' 'CAVALIER 4C' 'SABLE'
 'FORENZA' 'ELANTRA' 'LIBERTY 2WD V6' 'MALIBU 4C' 'CENTURY V6'
 'MUSTANG V6' 'STRATUS 4C' 'EXPLORER 4WD V6' 'TRIBUTE 2WD 4C'
 'NITRO 2WD V6' 'FREESTYLE FWD V6' 'MAZDA3' 'TRAILBLAZER 2WD 6C'
 'EXPEDITION 2WD V8' 'FREESTAR FWD V6' 'F150 PICKUP 2WD V8'
 'MALIBU MAXX V6' 'MARINER 2WD V6' 'VUE 2WD 4C' 'SORENTO 2WD' 'MILAN 4C'
 'F150 PICKUP 4WD V8' 'LACROSSE' 'MONTANA FWD' 'QUEST' 'SONATA 4C'
 'CARAVAN FWD 4C' 'CARAVAN FWD V6' 'EXPLORER 2WD V6' 'ENVOY XL 2WD 6C'
 'CAMRY 4C' 'CHARGER' 'FUSION 4C' 'SONOMA PICKUP 2WD 4C'
 'I-280 PICKUP 2WD 4C' 'F150 PICKUP 2WD V6' 'ESCAPE 2WD 4C'
 'ENVOY XL 4WD 6C' 'VUE 2WD V6' 'CHARGER V6' 'DURANGO 2WD V6' 'VERSA'
 'VENTURE FWD V6' 'MOUNTAINEER AWD V8' 'SENTRA' 'AURA' 'XTERRA 2WD V6'
 'EXPLORER 2WD V8' 'RONDO 4C' 'COMMANDER 4WD V6' 'RAIDER 2WD V6'
 'RELAY 2WD V6' 'VIBE' 'LS V8' 'VUE AWD 4C' 'SX4' 'COMMANDER 2WD V6'
 'EXPEDITION 4WD V8' 'GRAND AM V6' 'TUCSON 2WD V6' 'SUNFIRE' 'GRAND AM 4C'
 'MONTE CARLO' 'RENDEZVOUS FWD' 'ENVOY XL 2WD V8' 'FUSION V6'
 'AVIATOR 2WD V8' 'S SERIES' 'PATHFINDER 4WD V6' 'XTERRA 2WD 4C'
 'ENVOY 4WD 6C' 'YUKON 2WD V8' 'EXPLORER 4WD V8' 'PACIFICA AWD'
 'BONNEVILLE' 'ACCENT' 'LE SABRE' 'RX330 FWD' 'OUTLANDER 2WD 4C'
 'HIGHLANDER 2WD V6' 'ALERO 4C' 'MAXIMA' 'XG 350' 'SANTA FE 2WD V6' 'RIO'
 'COROLLA' 'SANTA FE 4WD V6' 'XTERRA 4WD V6' 'TERRAZA FWD V6' 'MILAN V6'
 'ESCAPE 4WD V6' 'TUCSON 4WD V6' 'MOUNTAINEER 2WD V6' 'PATHFINDER 2WD V6'
 'COMPASS 4WD 4C' 'CTS' 'TORRENT FWD V6' 'LIBERTY 2WD 4C'
 'TACOMA PICKUP 2WD V6' 'G5 4C' 'SANTA FE 2WD 4C' 'MOUNTAINEER AWD V6'
 'ENDEAVOR FWD' 'ECLIPSE' 'INTREPID' 'YUKON XL 1500 2WD' 'ASCENDER 4WD 6C'
 'AURA V6' 'SEDONA' 'XL-7 2WD' 'ESCAPE 4WD 4C' 'S10 PICKUP 2WD 4C'
 'MARINER 4WD V6' 'RENDEZVOUS AWD' 'MURANO 2WD V6' 'FREESTYLE AWD V6'
 'RONDO V6' 'CX-7 AWD 4C' 'MONTEREY' 'TRACKER 2WD 4C' 'VOYAGER FWD 4C'
 'SRX AWD V6' 'XB' 'PATRIOT 2WD 4C' 'NITRO 4WD V6' 'ELEMENT 2WD'
 'RAINIER RWD V8' 'MONTANA' 'TAHOE 2WD' 'MONTERO SPORT 4WD V6' 'MAZDA5'
 'MUSTANG V8' 'EQUINOX AWD V6' 'OUTBACK' 'SPORTAGE 2WD 4C' 'AMANTI'
 'DAKOTA PICKUP 4WD V8' 'XA' 'PRIZM' '4 RUNNER 2WD V8' 'FREESTYLE 2WD V6'
 'TRIBUTE 2WD V6' 'WRANGLER 6C' 'TIBURON' 'M35' 'SUBURBAN 1500 4WD'
 'SORENTO 4WD' 'SPORTAGE 2WD V6' 'COMMANDER 2WD V8' 'VERONA'
 'TRACKER 4WD 4C' '300M' 'CAMRY V6' 'TAURUS X FWD V6' 'REGAL'
 'ARMADA 2WD V8' 'ES330' 'CONCORDE' 'GALANT V6' 'TITAN PICKUP 4WD V8'
 'TRACKER 2WD V6' 'GRAND MARQUIS' 'TUNDRA PICKUP 4WD V8' 'ENVOY 2WD V8'
 'RX400H AWD' 'TUCSON 2WD 4C' 'PILOT' 'FRONTIER PICKUP 4WD' '3.2 TL'
 'ASPEN 2WD V8' 'VUE AWD V6' 'MAGNUM V8' 'FIREBIRD V6' 'AVIATOR AWD V8'
 'TRAILBLAZER 2WD V8' 'VOYAGER FWD V6' 'YUKON XL 1500 4WD'
 'CAMRY SOLARA V6' 'CAMRY SOLARA 4C' 'MATRIX 2WD' 'XG 300' 'G35'
 'SPORTAGE 4WD V6' 'FORESTER AWD' 'TUNDRA PICKUP 2WD V6' 'SOLSTICE'
 'F150 PICKUP 4WD V6' 'G8 V8' 'AERIO' 'UPLANDER AWD V6' 'PROTEGE 5'
 'HIGHLANDER 2WD 4C' 'EDGE FWD V6' 'CANYON PICKUP 2WD 4C' 'TRIBUTE 4WD V6'
 'MARINER 2WD 4C' 'CONTINENTAL' 'RAINIER RWD V6' 'RAINIER AWD V6'
 'MONTERO 4WD V6' 'PROTEGE' 'FX35 AWD' 'EXPLORER AWD V6' 'ELEMENT 4WD'
 'TSX' 'CROWN VICTORIA' 'SILHOUETTE' 'COLORADO PICKUP 4WD' 'ES300'
 'TOWN CAR' 'CARAVAN SE' 'ZEPHYR' 'COMPASS 2WD 4C' 'RAV-4 2WD'
 'LUCERNE V6' 'SEQUOIA 2WD' 'CARAVAN GRAND AWD V6' 'BRAVADA AWD V6'
 'YUKON 4WD V8' 'I30' 'PARK AVENUE' 'SIENNA' 'YUKON AWD V8'
 'DAKOTA PICKUP 4WD V6' 'COOPER' 'ENDEAVOR AWD' 'COUPE' 'CR-V 4WD'
 'NAVIGATOR 2WD V8' 'ECHO' 'RODEO 2WD V6' 'SCION XB' 'I-290 PICKUP 2WD 4C'
 'TRIBUTE 4WD 4C' 'QX4 4WD V6' 'B3000 PICKUP 2WD V6' 'ODYSSEY'
 'AXIOM 2WD V6' 'CAMARO V6' 'RSX' 'RAV-4 4WD' 'MIATA MX-5' 'S40'
 'TACOMA PICKUP 2WD 4C' 'ESCAPE' 'JETTA 5C' 'PASSAT 4C' 'AVALON'
 'ENTOURAGE' 'XL-7 4WD' 'CELICA' 'TC' 'MOUNTAINEER 2WD V8' 'CR-V 2WD'
 'JETTA 4C' 'VIBE AWD' 'COOPER S' 'FJ CRUISER 4WD V6' 'MAGENTIS 4C'
 'MR2 SPYDER' 'PATRIOT FWD 4C' 'LIBERTY 4WD 4C' 'JOURNEY FWD 4C' 'GS300'
 'TORRENT AWD V6' '1500HD SIERRA PICKUP' 'NAVIGATOR 4WD V8'
 'S10 PICKUP 2WD V6' 'RABBIT']

For Trim:

['GT' 'XLT' 'Bas' 'LS' '4540' 'LT' 'CX' 'SLT' 'Cla' 'Tou' 'SXT' 'ST' 'SE'
 'i' 'STX' 'GLS' '2' 'EX' 'LX' 'RT' '150' 'ZX4' 'Lim' 'Nor' 'Lar' 'GL'
 'Spo' 'SEL' 'SES' 'XL' '1' 'Cus' 'SLE' 'L10' 'Edd' 'LE' 'ZX3' 'S' 'ES'
 'XLS' 'R/T' 'Adv' 'LXi' 'SE-' 's' 'GLE' 'L30' 'Sta' 'GS' 'Z71' 'SL1'
 'SR5' 'Pro' 'L20' 'ZTS' 'CXL' 'ZR2' 'GTP' 'Sig' 'DE' 'ZX5' 'ZXW' 'SX'
 'Ren' 'ZTW' 'W/T' 'Her' 'Hig' 'CE' '3' 'XE' 'SV6' 'Edg' 'Den' 'OZ' 'SS'
 'LTZ' 'SC2' 'Plu' 'Lux' 'DX' 'Ove' 'Pre' 'GTC' 'SL2' 'VP' 'Exe' 'ZX2'
 'GX' 'SL' 'SVT' 'LW3' 'L' 'Val' 'L 3' 'Spy' 'Kin' 'Har' 'eC' 'EX-' 'LL'
 'X' 'GTS' 'XR' 'FX4' 'SC1' 'GXP' 'Dur' 'CXS' 'Max' 'eL' 'GXE' 'Si' 'Maz'
 'LW2' 'RS' 'Ent']

For SubModel:

['4D SEDAN' '4D CUV 3.0L XLT' 'MINIVAN 3.3L' 'EXT CAB 4.3L'
 '4D SUV 4.6L XLT' '4D CUV 2.2L' '4D SEDAN LS' '4D SEDAN LT' '4D SUV CX'
 'REG CAB 4.3L' 'QUAD CAB 4.7L ST' '4D SEDAN CLASSIC' '4D SPORT TOURING'
 'PASSENGER EXT 3.5L LS' '4D SUV 3.7L' 'PASSENGER EXT 3.5L' '2D COUPE'
 '4D SEDAN I' 'WAGON 2.7L' 'REG CAB 4.2L STX' '4D SEDAN SE'
 '4D SEDAN LEVEL 2' '4D SPORT UTILITY EX' '4D SUV 4.0L PREMIER'
 '4D SUV 2.2L LT' 'MINIVAN 3.3L LX' '2D COUPE LT' 'WAGON R/T'
 '4D SEDAN SE FFV' '4D SUV-PICKUP 5.3L' 'MINIVAN 3.3L SE'
 '4D SEDAN ZX4 ST' 'PASSENGER 3.8L LX' 'EXT CAB 4.6L STX'
 '4D SEDAN LIMITED' '4D SUV 4.2L LS' '4D SEDAN EX' '4D SPORT'
 '4D WAGON CX' '4D SEDAN LS CLASSIC' '4D WAGON LAREDO' '4D SEDAN LT 3.5L'
 '4D SEDAN GL2' '4D SUV LS' 'REG CAB 4.7L' '4D SEDAN TOURING'
 '4D SEDAN LX' '4D SUV 4.7L' 'QUAD CAB 5.7L' '4D SEDAN SE COMFORT'
 '4D SEDAN SE SVG' 'PASSENGER EXT 3.9L LS' 'WAGON 3.5L SXT'
 '4D SEDAN 2.7L' 'EXT CAB 4.2L XLT' '4D SEDAN LEVEL 1' '4D CUV 3.0L SE'
 '4D WAGON' '4D SUV LT' '4D SEDAN GT' '4D SEDAN CUSTOM'
 'PASSENGER 3.9L LX' 'MINIVAN 2.4L SE' '4D SEDAN LS PREMIUM'
 'REG CAB 2.3L EDGE' '4D SEDAN SXT' 'CREW CAB 3.5L SL' '4D SEDAN 1.8'
 'MINIVAN 3.3L FFV SPORT' '4D SEDAN EX AUTO' 'QUAD CAB 4.7L SLT'
 '4D SUV 5.4L XLT' '4D SEDAN SE1' '4D SUV 5.4L' '2D COUPE EX AUTO'
 '4D UTILITY 5.3L LS' '4D SUV 4.6L EDDIE BAUER' '4D SEDAN GLS'
 '4D SEDAN LT 3.9L' '4D SUV 5.4L EDDIE BAUER' '4D SEDAN LE' '4D SEDAN SES'
 '4D SEDAN LX AUTO' '4D SEDAN ES' '4D WAGON SXT' '4D SEDAN GT2'
 '2D COUPE ZX3' '4D SEDAN SES DURATEC' '4D UTILITY 5.3L FFV LS'
 '4D SUV 4.7L SLT' '4D SUV' 'EXT CAB 4.2L W/T' '4D SEDAN S' '4D SUV SPORT'
 '4D SUV SPORT 2.4L' '4D SUV 4.0L SPORT TRAC' '4D SUV 5.3L FFV'
 'MINIVAN 2.4L' '4D SEDAN ZX4' '4D SEDAN R/T' '4D SUV 4.7L ADVENTURER'
 '4D SUV 5.7L SLT' '4D SPORT UTILITY SE' '4D MINIVAN EXT 3.4L'
 '4D SPORT UTILITY I' '4D UTILITY 5.3L SLT' '2D COUPE SE'
 'MINIVAN 3.8L LXI' 'EXT CAB 5.3L LS' '4D SUV 4.8L LS'
 '4D SPORT UTILITY LX AUTO' '4D SEDAN SL' '4D SEDAN 2.5 S'
 '2D CONVERTIBLE TOURING' '4D SEDAN SE-R' '4D SEDAN SEL AWD'
 'PASSENGER 3.8L' '4D SUV 2.2L' '4D CUV 3.5L GLS' 'PASSENGER EXT 3.4L'
 '4D UTILITY 5.3L SLE' '4D CUV 2.3L XLS' '4D CUV GLS' '2D COUPE GT1'
 'CREW CAB 5.6L' 'PASSENGER 3.4L' 'MINIVAN 3.8L SXT' 'PASSENGER 3.5L LS'
 '4D SEDAN GLE' 'REG CAB 5.3L' '4D SEDAN L300' 'PASSENGER 3.9L SE'
 '4D SUV SPORT 2.0L' '4D SEDAN AWD 3.5L' 'EXT CAB 3.9L SPORT'
 '4D SUV 4.7L ST' 'REG CAB 5.9L SLT' '4D SEDAN SEL' 'EXT CAB 4.8L'
 '4D SUV 4.0L FFV XLS' 'QUAD CAB 4.7L' '4D SEDAN SXT FFV'
 '4D SEDAN SEL DURATEC' '4D SPORT UTILITY LS' 'QUAD CAB 3.7L'
 '2D COUPE SXT' '4D SUV CXL' '2D COUPE GS' 'CREW CAB 5.3L LS'
 '4D SUV 4.7L FFV SXT' '4D SUV 5.3L FFV LS' 'REG CAB 4.6L STX'
 '4D SUV 4.2L' '4D SPORT UTILITY LX' 'EXT CAB 2.4L XE' 'QUAD CAB 5.7L SLT'
 '4D SEDAN SL1' '4D SPORT TOURER' '4D CUV 3.0L XLS' 'MINIVAN 3.3L FFV SE'
 '2D CONVERTIBLE' 'CREW CAB 4.7L SR5' '2D COUPE GL2' '4D SEDAN GS'
 '2D SUV 4.0L SPORT XLS' '5D SEDAN I' '4D HATCHBACK AWD' '4D SEDAN L200'
 '4D SEDAN LT 3.5L FFV' '4D SEDAN LS 3.5L FFV' 'EXT CAB 5.6L LE'
 '4D SUV 2.2L LS' '4D SEDAN ZTS' '4D SUV 2.2L PANEL LS' '4D CUV 2.7L GLS'
 'WAGON 3.5L' '4D WAGON SE' '4D SUV LIMITED' '4D SEDAN CXL' '2D COUPE LS'
 '4D SPORT UTILITY' 'REG CAB 4.3L LS' 'PASSENGER 3.9L LS'
 '4D SUV HARDTOP 2.5L ZR2' '4D SEDAN GTP' '4D UTILITY 4.2L SLE'
 '2D COUPE GT' '4D SEDAN 2.7L SE' '4D SEDAN SIGNATURE' '4D CUV 3.0L SEL'
 '4D SUV 4.0L XLS' '4D SEDAN LUXURY' '4D SEDAN DE' '4D SUV 4.6L XLS'
 '4D PASSENGER 3.9L SES' '4D SUV 5.4L XLS' 'SPORT UTILITY 7 PASSENGER'
 '4D SUV 5.3L LT' '4D SEDAN LXI' '2D QUAD COUPE LEVEL 2' 'EXT CAB 5.4L XL'
 '2D CONVERTIBLE GLS' '3D EXT CAB 4.3L' '4D SEDAN ZX5' '2D HATCHBACK ZX3'
 'WAGON LX' '4D SEDAN CX' '4D UTILITY 5.3L' '4D WAGON SX' 'MINIVAN 3.8L'
 'EXT CAB 5.4L LARIAT' '4D UTILITY 4.8L SLE' '4D SUV 5.9L SLT'
 '4D WAGON SPORT' '4D SUV 4.7L SPORT' '4D SPORT UTILITY SL' '4D WAGON ZTW'
 '2D HATCHBACK' '4D CUV 3.0L' 'REG CAB 4.2L XL' '4D SUV 4.7L LIMITED'
 '2D CONVERTIBLE LX' 'QUAD CAB 3.7L SLT' '4D SUV HARDTOP 2.2L LT'

In [27]:
X_valid.loc[X_valid.Transmission == 'Manual', 'Transmission'] = 'MANUAL'

Make и ещё признаки убрали из категорильаных, так как для него надо другой encoder применить, ибо в valid есть значения , которых в train нет.

In [28]:
categorical_columns.remove('Make')
categorical_columns.remove('Model')
categorical_columns.remove('Trim')
categorical_columns.remove('SubModel')
categorical_columns.remove('VNST')

transformers = [
    ('num', StandardScaler(), numeric_columns),
    ('cat', OneHotEncoder(), categorical_columns),
    ('count_scaled', Pipeline([
        ('count', CountEncoder()),
        ('scaler', StandardScaler())
    ]), ['Make', 'Model', 'Trim', 'SubModel', 'VNST'])
]

ct = ColumnTransformer(transformers, remainder='drop')
X_train_transform = ct.fit_transform(X_train)
X_valid_transform = ct.transform(X_valid)
X_test_transform = ct.transform(X_test)

In [29]:
pd.DataFrame(X_train_transform, columns=ct.get_feature_names_out())

,num__RefId,num__VehYear,num__VehicleAge,num__WheelTypeID,num__VehOdo,num__MMRAcquisitionAuctionAveragePrice,num__MMRAcquisitionAuctionCleanPrice,num__MMRAcquisitionRetailAveragePrice,num__MMRAcquisitonRetailCleanPrice,num__MMRCurrentAuctionAveragePrice,...,cat__Size_VAN,cat__TopThreeAmericanName_CHRYSLER,cat__TopThreeAmericanName_FORD,cat__TopThreeAmericanName_GM,cat__TopThreeAmericanName_OTHER,count_scaled__Make,count_scaled__Model,count_scaled__Trim,count_scaled__SubModel,count_scaled__VNST
0,-0.241741,1.357265,-1.357240,-0.198594,0.608776,0.586988,0.656821,0.585911,0.655256,1.152128,...,0.0,1.0,0.0,0.0,0.0,-0.370581,-0.646739,1.495516,-0.519523,-0.303717
1,-0.240930,0.109884,-0.109905,-0.199010,-2.251226,-0.556616,-0.464911,-0.550313,-0.459592,-0.375865,...,1.0,0.0,1.0,0.0,0.0,0.383908,0.094845,-1.040652,-0.646551,-0.303717
2,-0.240882,-0.513807,0.513762,-0.198594,0.128598,-1.082305,-1.065826,-1.072680,-1.056844,-0.983284,...,0.0,1.0,0.0,0.0,0.0,0.647220,-0.113505,0.838189,0.090533,-0.303717
3,-0.240835,0.733574,-0.733573,-0.199010,-0.027052,1.095836,1.025344,1.091309,1.021473,1.350313,...,0.0,0.0,0.0,1.0,0.0,1.090292,-0.802119,0.574783,-0.576632,-0.303717
4,-0.240787,-0.513807,0.513762,-0.199010,-0.231833,-1.083909,-1.005124,-1.074156,-0.996689,-0.994539,...,0.0,0.0,1.0,0.0,0.0,0.383908,2.376099,-1.040652,-0.640146,-0.303717
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24322,0.926504,0.109884,-0.109905,-0.198594,0.048183,-1.061454,-1.083785,-1.052022,-1.074692,-1.083381,...,0.0,0.0,0.0,1.0,0.0,1.090292,-0.756211,0.574783,1.945785,0.082387
24323,0.926456,1.980956,-1.980908,-0.198594,-0.387833,1.126711,0.833898,1.122297,0.831093,0.853042,...,0.0,1.0,0.0,0.0,0.0,0.647220,-0.021690,0.838189,1.945785,0.082387
24324,0.926409,1.980956,-1.980908,-0.198594,-0.372226,1.126711,0.833898,1.122297,0.831093,1.095447,...,0.0,1.0,0.0,0.0,0.0,0.647220,-0.021690,0.838189,1.945785,0.082387
24325,-1.030312,0.733574,-0.733573,-0.198594,0.586100,1.164805,1.253066,1.159925,1.247550,0.702293,...,0.0,0.0,0.0,0.0,1.0,-1.674985,-0.915122,-1.156930,-0.638545,1.523458
24326,-1.030264,0.733574,-0.733573,-0.198594,-0.192151,0.285048,0.445261,0.285992,0.444714,0.252055,...,1.0,1.0,0.0,0.0,0.0,0.647220,0.847023,1.495516,-0.395163,1.523458

# 4. Train LogisticRegression, GaussianNB, KNN from sklewrn on the traning dataset and chek the quality of your algorithms on the validation  dataset.

In [30]:
log_reg = LogisticRegression()
log_reg.fit(X_train_transform, y_train)

knn = KNeighborsClassifier()
knn.fit(X_train_transform, y_train)

naive_baues = GaussianNB()
naive_baues.fit(X_train_transform, y_train)

GaussianNB()

In [31]:
def my_simple_gini(y_true, y_preduct):
    return abs(2*roc_auc_score(y_true, y_preduct) - 1)

In [32]:
log_reg_gini = my_simple_gini(y_valid, log_reg.predict_proba(X_valid_transform)[:,1])
knn_gini = my_simple_gini(y_valid, knn.predict_proba(X_valid_transform)[:,1])
naive_baues_gini = my_simple_gini(y_valid, naive_baues.predict_proba(X_valid_transform)[:,1])

print(f'Logistic Regression gini: {log_reg_gini}')
print(f'KNN gini: {knn_gini}')
print(f'Gaussian Naive Bauys gini: {naive_baues_gini}')

Logistic Regression gini: 0.4226569656305825
KNN gini: 0.3411520019186498
Gaussian Naive Bauys gini: 0.41939355200516903

Лучше всего получилось у логистической регрессии. Скорее всего для KNN надо лучше подбирать гиперпараметры, а на классических получается очень плохой результат. Гауссовский наивный байес справился чуть хуже, может быть из-за зависимости признаков или просто распредления признаков не совсем нормальными являются.

# 5. Implement Gini score colculation. You can use the 2*ROC AUC - 1 approach, so you need to implement the ROC AYC calculation.

In [33]:
def calculate_roc_auc(y_true, y_score):
    data = list(zip(y_score, y_true))
    data_sorted = sorted(data, key=lambda x: x[0], reverse=True)

    thresholds = sorted(set(y_score), reverse=True)
    thresholds.append(1.0)
    thresholds = sorted(thresholds, reverse=True)

    P = sum(y_true) # всего реальных 1
    N = len(y_true) - P # всего реальных 0

    fpr_points = []
    tpr_points = []

    for threshold in thresholds:
        TP = 0
        FP = 0

        for score, true_class in data_sorted:
            if score >= threshold:
                if true_class == 1:
                    TP += 1
                else:
                    FP += 1
        
        TPR = TP / P if P > 0 else 0
        FPR = FP / N if N > 0 else 0

        fpr_points.append(FPR)
        tpr_points.append(TPR)
    
    fpr_points.append(1.0)
    tpr_points.append(1.0)

    points = sorted(zip(fpr_points, tpr_points), key=lambda x: x[0])
    fpr_sorted, tpr_sorted = zip(*points)

    auc = 0.0
    for i in range(1, len(fpr_points)):
        width = fpr_sorted[i] - fpr_sorted[i-1]
        avg_height = (tpr_sorted[i] + tpr_sorted[i-1]) / 2
        auc += width * avg_height

    return auc

In [34]:
y_score = log_reg.predict_proba(X_valid_transform)[:,1]
print(f'sklearn:  {roc_auc_score(y_valid, y_score)}')
print(f'my function: {calculate_roc_auc(y_valid.values, y_score)}')

sklearn:  0.7113284828152913
my function: 0.7113284828152948

In [35]:
def my_gini_score(y_true, y_preduct):
    return abs(2*calculate_roc_auc(y_true, y_preduct) - 1)

In [36]:
log_reg_gini = my_gini_score(y_valid, log_reg.predict_proba(X_valid_transform)[:,1])
knn_gini = my_gini_score(y_valid, knn.predict_proba(X_valid_transform)[:,1])
naive_baues_gini = my_gini_score(y_valid, naive_baues.predict_proba(X_valid_transform)[:,1])

print(f'Logistic Regression gini: {log_reg_gini}')
print(f'KNN gini: {knn_gini}')
print(f'Gaussian Naive Bauys gini: {naive_baues_gini}')

Logistic Regression gini: 0.42265696563058963
KNN gini: 0.3408471043604653
Gaussian Naive Bauys gini: 0.41294445779826905

значения получились близкие к тем, в которых roc_auc считался при помощи sklearn

# 6. Implement your own version of LogisticRegression, KNN and NaiveBayes classifier.

### LogisticRegression

In [37]:
class myLogisticRegression:
    def __init__(self, learning_rate=0.01, n_epochs=1000, batch_size=32, random_state=21, alpha=0.01):
        self.lr = learning_rate
        self.n_epochs = n_epochs
        self.batch_size = batch_size
        self.w = None
        self.random_state = random_state
        self.alpha = alpha

    def _sigmoid(self, z):
        z = np.clip(z, -500, 500)
        return 1 / (1 + np.exp(-z))

    def fit(self, X_input, y):
        X = np.hstack((np.ones((X_input.shape[0], 1)), X_input)) # X с столбцом из единиц для свободного члена
        self.w = np.zeros(X.shape[1]) # вектор весов
        np.random.seed(self.random_state)

        for epoch in range(self.n_epochs):
            indices = np.arange(len(X))
            np.random.shuffle(indices)
            
            for i in range(0, len(X), self.batch_size):
                batch_indices = indices[i:i+self.batch_size]

                X_batch = X[batch_indices] # берём батч из всего X
                Y_batch = y[batch_indices]

                P_batch = self._sigmoid(X_batch @ self.w) # вычилсяем вероятности

                gradient = (1 / self.batch_size) * (X_batch.T @ (P_batch - Y_batch))

                self.w -= self.lr * gradient
        
    
    def predict_proba(self, X_input):
        X = np.hstack((np.ones((X_input.shape[0], 1)), X_input))
        P = self._sigmoid(X @ self.w)

        return P
    
    def predict(self, X_input, threshold=0.5):
        X = np.hstack((np.ones((X_input.shape[0], 1)), X_input))
        P = self._sigmoid(X @ self.w)


        predictions = (P >= threshold).astype(int)
        
        return predictions

In [38]:
my_log_reg = myLogisticRegression()
my_log_reg.fit(X_train_transform, y_train.values)

In [39]:
my_log_reg_gini = my_simple_gini(y_valid, my_log_reg.predict_proba(X_valid_transform))

print(f'Logistic Regression gini: {log_reg_gini}')
print(f'My Logistic Regression gini: {my_log_reg_gini}')

Logistic Regression gini: 0.42265696563058963
My Logistic Regression gini: 0.43980173234152886

На валидационной выборке моя модель получила даже чуть выше значения, скорее всего из-за чуть лучшего подбора гиперпараметров и количсетва итераций.

### KNN

In [40]:
class my_KNN:
    def __init__(self, n_neighbors=5):
        self.n_neighbors = n_neighbors

    def fit(self, X, y):
        self.train_features = X
        self.train_target = y

    def get_neighbors(self, X_point):
        differences = self.train_features - X_point
        distances = np.sqrt(np.sum(differences ** 2, axis=1))

        all_neighbors = np.column_stack([distances, self.train_target])

        sorted_indices = np.argsort(all_neighbors[:,0])[:self.n_neighbors]
        nearest_n_neighbors = all_neighbors[sorted_indices]

        return nearest_n_neighbors[:,1]

    def predict_proba(self, X):
        return [self.get_neighbors(point).mean() for point in tqdm(X, desc='KNN Prediction', total=len(X))]
    
    def predict(self, X):
        predictions = (self.predict_proba(X) >= 0.5).astype(int)
        
        return predictions

In [41]:
my_knn = my_KNN()
my_knn.fit(X_train_transform, y_train)

In [42]:
my_knn_predict_proba = my_knn.predict_proba(X_valid_transform)

KNN Prediction: 100%|██████████| 24323/24323 [05:03<00:00, 80.04it/s]

In [43]:
my_knn_gini = my_simple_gini(y_valid, my_knn_predict_proba)

print(f'KNN gini: {knn_gini}')
print(f'My KNN gini: {my_knn_gini}')

KNN gini: 0.3408471043604653
My KNN gini: 0.3411520019186498

### Guassian Naive Bayes

In [44]:
class my_GuassionNaiveBayes:
    def __init__(self, var_smoothing=1e-09):
        self.var_smoothing = var_smoothing

    def fit(self, X, y):
        n_0 = (y == 0).sum() # число объектов y = 0
        n_1 = (y == 1).sum() # число объектов y = 1

        self.P_y_0 = n_0 / (n_0 + n_1) # P(y=0)
        self.P_y_1 = n_1 / (n_0 + n_1) # априорные вероятности P(y=1)

        X_y_0 = X[y == 0]
        self.mean_y_0 = X_y_0.mean(axis=0)
        self.var_y_0 = X_y_0.var(axis=0) + self.var_smoothing

        X_y_1 = X[y == 1]
        self.mean_y_1 = X_y_1.mean(axis=0)
        self.var_y_1 = X_y_1.var(axis=0) + self.var_smoothing

    def predict_proba(self, X):
        score_0 = np.log(self.P_y_0) + np.sum((((-1/2) * np.log(2 * np.pi * self.var_y_0)) - (((X - self.mean_y_0)**2) / (2*self.var_y_0))), axis=1)
        score_1 = np.log(self.P_y_1) + np.sum((((-1/2) * np.log(2 * np.pi * self.var_y_1)) - (((X - self.mean_y_1)**2) / (2*self.var_y_1))), axis=1)

        max_score = np.maximum(score_0, score_1)
        exp_score_0 = np.exp(score_0 - max_score)
        exp_score_1 = np.exp(score_1 - max_score)

        proba_1 = exp_score_1 / (exp_score_0 + exp_score_1)
        return proba_1
    
    def predict(self, X):
        predictions = (self.predict_proba(X) >= 0.5).astype(int)
        return predictions

In [45]:
my_guassianNB = my_GuassionNaiveBayes()
my_guassianNB.fit(X_train_transform, y_train)

In [46]:
my_guassianNB.predict_proba(X_valid_transform)

array([9.11075755e-03, 1.39697313e-03, 2.08713693e-04, ...,
       5.90294596e-05, 9.82326968e-05, 3.71502042e-02], shape=(24323,))

In [47]:
print(f'GuassianNB gini: {naive_baues_gini}')
print(f'My guassianNB gini: {my_simple_gini(y_valid, my_guassianNB.predict_proba(X_valid_transform))}')

GuassianNB gini: 0.41294445779826905
My guassianNB gini: 0.419421633888835

# 7. Try to create non-linear features, for example:
- fractions: feature1 / feature2
- groupby features: df[‘categorical_feature’].map(df.groupby(‘categorical_feature’)[‘continious_feature’].mean())

Add new features to your pipeline, repeat step 4. Did you manage to increase your Gini score (you should!)?

In [48]:
numeric_selector = make_column_selector(dtype_include=['int64', 'float64'])
numeric_columns_for_make_non_linear = numeric_selector(X_train)
numeric_columns_for_make_non_linear

['RefId',
 'VehYear',
 'VehicleAge',
 'WheelTypeID',
 'VehOdo',
 'MMRAcquisitionAuctionAveragePrice',
 'MMRAcquisitionAuctionCleanPrice',
 'MMRAcquisitionRetailAveragePrice',
 'MMRAcquisitonRetailCleanPrice',
 'MMRCurrentAuctionAveragePrice',
 'MMRCurrentAuctionCleanPrice',
 'MMRCurrentRetailAveragePrice',
 'MMRCurrentRetailCleanPrice',
 'BYRNO',
 'VNZIP1',
 'VehBCost',
 'IsOnlineSale',
 'WarrantyCost']

Функция для деления одного признака на другой, тут есть условие, что не должны быть inf или все 0 или все одинаковые значения

In [49]:
def division_of_fearures(X, numeric_columns):   
    X_non_linear = X.copy()
    new_columns = {}

    for i in range(len(numeric_columns)):
        for j in range(len(numeric_columns)):
            if i != j:
                col_name = f'{numeric_columns[i]}/{numeric_columns[j]}'
                new_column = X_non_linear[numeric_columns[i]] / X_non_linear[numeric_columns[j]]
                
                new_columns[col_name] = new_column
                
    new_df = pd.DataFrame(new_columns).fillna(0)
    X_non_linear = pd.concat([X_non_linear, new_df], axis=1)

    return X_non_linear

Функция для доабвления средних по катогрии или же по категорильному признаку.

In [50]:
cat_columns_for_make_non_linear = cat_selector(X_train)
cat_columns_for_make_non_linear

['Auction',
 'Make',
 'Model',
 'Trim',
 'SubModel',
 'Color',
 'Transmission',
 'WheelType',
 'Nationality',
 'Size',
 'TopThreeAmericanName',
 'VNST']

In [51]:
class goupby_features:
    def __init__(self):
        pass

    def fit(self, X, cat_columns, numeric_columns):
        self.cat_columns = cat_columns
        self.numeric_columns = numeric_columns
        self.cat_means_all = {}
        self.global_means = {}

        for numeric in self.numeric_columns:
            self.global_means[numeric] = X[numeric].mean()

        for category in self.cat_columns:
            for numeric in self.numeric_columns:
                key = f'{category}_{numeric}'
                category_means = X.groupby(category)[numeric].mean()
                self.cat_means_all[key] = category_means
    
    def transform(self, X):
        X_goruped_features = X.copy()
        new_columns = {}

        for category in self.cat_columns:
            for numeric in self.numeric_columns:
                key = f'{category}_{numeric}'
                new_col_name = f'{category}_{numeric}_mean'

                global_mean = self.global_means[numeric]
                new_columns[new_col_name] = X_goruped_features[category].map(self.cat_means_all[key]).fillna(global_mean)

        new_columns_df = pd.DataFrame(new_columns, index=X_goruped_features.index)
        X_goruped_features = pd.concat([X_goruped_features, new_columns_df], axis=1)

        return X_goruped_features

### Добавление функция для создания нелинейных функций и применеие всех кодеров и нормализаций

Деление

In [52]:
X_train_fractions = division_of_fearures(X_train, numeric_columns_for_make_non_linear)
X_valid_fractions = division_of_fearures(X_valid, numeric_columns_for_make_non_linear)
X_test_fractions = division_of_fearures(X_test, numeric_columns_for_make_non_linear)

columns_to_del = []

for column in numeric_selector(X_train_fractions):
    if (X_train_fractions[column].nunique() <= 1) or ((X_train_fractions[column] == 0).all()) or (np.isinf(X_train_fractions[column]).any())\
        or (X_valid_fractions[column].nunique() <= 1) or ((X_valid_fractions[column] == 0).all()) or (np.isinf(X_valid_fractions[column]).any())\
        or (X_test_fractions[column].nunique() <= 1) or ((X_test_fractions[column] == 0).all()) or (np.isinf(X_test_fractions[column]).any()):
        columns_to_del.append(column)

X_train_fractions.drop(columns=columns_to_del, inplace=True)
X_valid_fractions.drop(columns=columns_to_del, inplace=True)
X_test_fractions.drop(columns=columns_to_del, inplace=True)

средние по категориям

In [53]:
numeric_columns_for_make_non_linear.remove('IsOnlineSale')
my_groupby_feature = goupby_features()
my_groupby_feature.fit(X_train_fractions, cat_columns_for_make_non_linear, numeric_columns_for_make_non_linear)

X_train_non_linear = my_groupby_feature.transform(X_train_fractions)
X_valid_non_linear = my_groupby_feature.transform(X_valid_fractions)
X_test_non_linear = my_groupby_feature.transform(X_test_fractions)

In [54]:
numeric_columns_after_addedd_nonlinear = numeric_selector(X_train_non_linear)

In [55]:
transformers = [
    ('num', StandardScaler(), numeric_columns_after_addedd_nonlinear),
    ('cat', OneHotEncoder(), categorical_columns),
    ('count_scaled', Pipeline([
        ('count', CountEncoder()),
        ('scaler', StandardScaler())
    ]), ['Make', 'Model', 'Trim', 'SubModel', 'VNST'])
]

ct = ColumnTransformer(transformers, remainder='drop')
X_train_transform_non_linear = ct.fit_transform(X_train_non_linear)
X_valid_transform_non_linear = ct.transform(X_valid_non_linear)
X_test_transform_non_linear = ct.transform(X_test_non_linear)

feature_names = ct.get_feature_names_out()

In [56]:
log_reg_non_linear = LogisticRegression()
log_reg_non_linear.fit(X_train_transform_non_linear, y_train)

knn_non_linear = KNeighborsClassifier()
knn_non_linear.fit(X_train_transform_non_linear, y_train)

naive_baues_non_linear = GaussianNB()
naive_baues_non_linear.fit(X_train_transform_non_linear, y_train)

c:\Users\User\anaconda3\envs\ml_projects\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

GaussianNB()

In [57]:
log_reg_gini = my_simple_gini(y_valid, log_reg.predict_proba(X_valid_transform)[:,1])
knn_gini = my_simple_gini(y_valid, knn.predict_proba(X_valid_transform)[:,1])
naive_baues_gini = my_simple_gini(y_valid, naive_baues.predict_proba(X_valid_transform)[:,1])

print(f'Результаты из пунка 4:')
print(f'Logistic Regression gini: {log_reg_gini}')
print(f'KNN gini: {knn_gini}')
print(f'Gaussian Naive Bauys gini: {naive_baues_gini}')

Результаты из пунка 4:
Logistic Regression gini: 0.4226569656305825
KNN gini: 0.3411520019186498
Gaussian Naive Bauys gini: 0.41939355200516903

In [58]:
log_reg_gini_non_linear = my_simple_gini(y_valid, log_reg_non_linear.predict_proba(X_valid_transform_non_linear)[:,1])
knn_gini_non_linear = my_simple_gini(y_valid, knn_non_linear.predict_proba(X_valid_transform_non_linear)[:,1])
naive_baues_gini_non_linear = my_simple_gini(y_valid, naive_baues_non_linear.predict_proba(X_valid_transform_non_linear)[:,1])

print(f'После добавления нелинейных признаков')
print(f'Logistic Regression gini: {log_reg_gini_non_linear}')
print(f'KNN gini: {knn_gini_non_linear}')
print(f'Gaussian Naive Bauys gini: {naive_baues_gini_non_linear}')

После добавления нелинейных признаков
Logistic Regression gini: 0.45923663641411316
KNN gini: 0.31519482643274843
Gaussian Naive Bauys gini: 0.3823841686528624

Для логистической регрессии улучшилось, для KNN и байеса наоборот узудшилось. Для наивного баеса так как признаки зависимые. Для knn просто из-за большоей размерности не всегда нелиненйные признаки делают лучше.

# 8. Determine the best features for the problem using the coefficiients of the logistic model. Try to aliminate unseless features by hand and by L1 regularization. Which approach is better it terms of Gini score ?

In [59]:
log_reg_l1 = LogisticRegression(penalty='l1', solver='liblinear')
log_reg_l1.fit(X_train_transform_non_linear, y_train)

LogisticRegression(penalty='l1', solver='liblinear')

In [60]:
weights_feature = pd.DataFrame({
    'feature_name' : feature_names,
    'Importance' : np.abs(log_reg_l1.coef_[0])
})

In [61]:
weights_feature

               feature_name  Importance
0                num__RefId    0.092790
1              num__VehYear    0.433186
2           num__VehicleAge    0.000000
3          num__WheelTypeID    0.057553
4               num__VehOdo    0.000000
..                      ...         ...
398      count_scaled__Make    0.070196
399     count_scaled__Model    0.151584
400      count_scaled__Trim    0.022279
401  count_scaled__SubModel    0.060890
402      count_scaled__VNST    0.077360

[403 rows x 2 columns]

In [62]:
weights_feature_sorted = weights_feature.sort_values('Importance', ascending=False)
weights_feature_sorted

                                          feature_name  Importance
51       num__MMRAcquisitionAuctionAveragePrice/VehOdo    1.160562
54   num__MMRAcquisitionAuctionAveragePrice/MMRAcqu...    1.083651
345        num__VNST_MMRCurrentRetailAveragePrice_mean    0.966717
79   num__MMRAcquisitonRetailCleanPrice/MMRAcquisit...    0.897190
81   num__MMRAcquisitonRetailCleanPrice/MMRAcquisit...    0.883221
..                                                 ...         ...
211                               num__Trim_BYRNO_mean    0.000000
216                         num__SubModel_VehYear_mean    0.000000
220  num__SubModel_MMRAcquisitionAuctionAveragePric...    0.000000
41                           num__WheelTypeID/VehBCost    0.000000
244         num__Color_MMRCurrentRetailCleanPrice_mean    0.000000

[403 rows x 2 columns]

In [63]:
weights_feature_sorted[weights_feature_sorted['Importance'] > 0]

                                          feature_name  Importance
51       num__MMRAcquisitionAuctionAveragePrice/VehOdo    1.160562
54   num__MMRAcquisitionAuctionAveragePrice/MMRAcqu...    1.083651
345        num__VNST_MMRCurrentRetailAveragePrice_mean    0.966717
79   num__MMRAcquisitonRetailCleanPrice/MMRAcquisit...    0.897190
81   num__MMRAcquisitonRetailCleanPrice/MMRAcquisit...    0.883221
..                                                 ...         ...
212                              num__Trim_VNZIP1_mean    0.001137
167                         num__Make_WheelTypeID_mean    0.000828
187    num__Model_MMRAcquisitionAuctionCleanPrice_mean    0.000724
255  num__Transmission_MMRAcquisitionAuctionCleanPr...    0.000655
233                            num__Color_VehYear_mean    0.000008

[187 rows x 2 columns]

In [64]:
top_100_features_indexes = weights_feature_sorted.index[:150]
top_100_features_indexes

Index([ 51,  54, 345,  79,  81, 348, 372,  78,  21, 203,
       ...
        28, 178, 229, 119, 231, 143, 201,  39,  40, 214],
      dtype='int64', length=150)

In [65]:
X_train_transform_non_linear[:,top_100_features_indexes].shape

(24327, 150)

In [66]:
X_train_important_features = X_train_transform_non_linear[:,top_100_features_indexes]
X_valid_important_features = X_valid_transform_non_linear[:,top_100_features_indexes]
X_test_important_features = X_test_transform_non_linear[:,top_100_features_indexes]

In [67]:
log_reg_important_features = LogisticRegression()
log_reg_important_features.fit(X_train_important_features, y_train)

knn_important_features = KNeighborsClassifier()
knn_important_features.fit(X_train_important_features, y_train)

naive_baues_important_features = GaussianNB()
naive_baues_important_features.fit(X_train_important_features, y_train)

c:\Users\User\anaconda3\envs\ml_projects\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

GaussianNB()

In [68]:
log_reg_gini_non_linear = my_simple_gini(y_valid, log_reg_non_linear.predict_proba(X_valid_transform_non_linear)[:,1])
knn_gini_non_linear = my_simple_gini(y_valid, knn_non_linear.predict_proba(X_valid_transform_non_linear)[:,1])
naive_baues_gini_non_linear = my_simple_gini(y_valid, naive_baues_non_linear.predict_proba(X_valid_transform_non_linear)[:,1])

print(f'По всем признакам')
print(f'Logistic Regression gini: {log_reg_gini_non_linear}')
print(f'KNN gini: {knn_gini_non_linear}')
print(f'Gaussian Naive Bauys gini: {naive_baues_gini_non_linear}')

По всем признакам
Logistic Regression gini: 0.45923663641411316
KNN gini: 0.31519482643274843
Gaussian Naive Bauys gini: 0.3823841686528624

In [69]:
log_reg_gini_important_features = my_simple_gini(y_valid, log_reg_important_features.predict_proba(X_valid_important_features)[:,1])
knn_gini_important_features = my_simple_gini(y_valid, knn_important_features.predict_proba(X_valid_important_features)[:,1])
naive_baues_gini_important_features = my_simple_gini(y_valid, naive_baues_important_features.predict_proba(X_valid_important_features)[:,1])

print(f'По топ 150 признакам')
print(f'Logistic Regression gini: {log_reg_gini_important_features}')
print(f'KNN gini: {knn_gini_important_features}')
print(f'Gaussian Naive Bauys gini: {naive_baues_gini_important_features}')

По топ 150 признакам
Logistic Regression gini: 0.453307385672826
KNN gini: 0.3142583553611811
Gaussian Naive Bauys gini: 0.3798022635073708

Самый высокий показатель gini  у логистичесокой регрессии.

# 9. Seelct your best model (algorithm + feature set) and tweak its hyperparameters to increase the Gini score on the validation dataset. Which hyperparameters have the modes impact ?

Модель с самым высоким показателем Gini - это Logistic Regression, и также я возьму топ 150 признаков по важности, полученные при помощи l1 регуляризации.

In [70]:
def gini_score(y_true, y_proba):
    auc = roc_auc_score(y_true, y_proba)
    return 2 * auc - 1

gini_scorer = make_scorer(
    gini_score,
    needs_proba=True,
    greater_is_better=True
)

In [71]:
param_grid = {
    'tol' : np.arange(0.0001, 0.001, 0.0001),
    'C' : [0.1, 1, 3, 10],
    'random_state' : [21],
    'solver' : ['lbfgs', 'newton-cg', 'newton-cholesky', 'sag', 'saga'],
}

clf = GridSearchCV(LogisticRegression(max_iter=1000), param_grid=param_grid, n_jobs=-1, scoring='roc_auc')

In [72]:
clf.fit(X_train_important_features, y_train)

GridSearchCV(estimator=LogisticRegression(max_iter=1000), n_jobs=-1,
             param_grid={'C': [0.1, 1, 3, 10], 'random_state': [21],
                         'solver': ['lbfgs', 'newton-cg', 'newton-cholesky',
                                    'sag', 'saga'],
                         'tol': array([0.0001, 0.0002, 0.0003, 0.0004, 0.0005, 0.0006, 0.0007, 0.0008,
       0.0009])},
             scoring='roc_auc')

In [73]:
clf.best_params_

{'C': 0.1,
 'random_state': 21,
 'solver': 'saga',
 'tol': np.float64(0.0009000000000000001)}

In [74]:
best_model_log_reg = LogisticRegression(C= 0.1, random_state=21, solver='saga', tol=0.0009, max_iter=1000)

best_model_log_reg.fit(X_train_important_features, y_train)

best_gini = gini_score(y_valid, best_model_log_reg.predict_proba(X_valid_important_features)[:,1])

print(f'Gini for best model: {best_gini}')

Gini for best model: 0.4624243633881784

# 10. Check the Gini scores on all three datasets for your best model: traning Gini, valid Gini, test Gini. Do you see a drop in performance when comparing the valid quality to the test quality? Is your model overfittied or not ? Explain.

In [75]:
best_gini_train = gini_score(y_train, best_model_log_reg.predict_proba(X_train_important_features)[:,1])
best_gini_valid = gini_score(y_valid, best_model_log_reg.predict_proba(X_valid_important_features)[:,1])
best_gini_test = gini_score(y_test, best_model_log_reg.predict_proba(X_test_important_features)[:,1])


print(f'Train Gini: {best_gini_train}')
print(f'valid Gini: {best_gini_valid}')
print(f'test Gini: {best_gini_test}')

Train Gini: 0.5300220224315852
valid Gini: 0.4624243633881784
test Gini: 0.4786409339986981

Как видно по метрикам, модель не переобучена, так как на тестовой выборке метрика даже выше, чем на валидационной. Это говорит о том, что на данных, которые раньше модель не видела ни при отборе признаков, ни при подборе гиперпараметров, даже при преобработке данных все средние занчения или категории из теста ничего не бралось. И при этом метрика на тесте очень не плохая.

# 11. Implement calculation of Racall, Precision, F1 score and AUC PR metrics. Compare your algorithms on the test dataset using AUC PR metric.

In [76]:
def calculate_TP_TN_FP_FN(y_true, y_predict):
    TP = 0
    TN = 0
    FP = 0
    FN = 0

    for i in range(len(y_true)):
        if y_true[i] == 1:
            if y_predict == 1:
                TP += 1
            else:
                FN += 1
        elif y_true[i] == 0:
            if y_predict[i] == 0:
                TN += 1
            else:
                FP += 1

    return TP, TN, FP, FN

In [77]:
def my_precision(y_true, y_predict):
    TP, TN, FP, FN = calculate_TP_TN_FP_FN(y_true, y_predict)

    return TP / (TP + FP)

In [78]:
def my_recall(y_true, y_predict):
    TP, TN, FP, FN = calculate_TP_TN_FP_FN(y_true, y_predict)

    return TP / (TP + FN)

In [79]:
def my_F1_score(y_true, y_predict):
    precision = my_precision(y_true, y_predict)
    recall = my_recall(y_true, y_predict)

    return 2 * (precision * recall) / (precision + recall)

In [80]:
def calculate_auc_pr(y_true, y_proba):
    indices = np.argsort(y_proba)[::-1]
    y_true_sorted = y_true.iloc[indices]
    y_proba_sorted = y_proba[indices]

    precisions = []
    recalls = []
    tp = 0
    fp = 0
    fn = np.sum(y_true_sorted == 1)
    tn = np.sum(y_true_sorted == 0)

    for i in range(len(y_true_sorted)):
        if y_true_sorted.iloc[i] == 1:
            tp += 1
            fn -= 1
        else:
            fp += 1
            tn -= 1
        precision = tp / (tp + fp) if (tp + fp) > 1 else 1
        recall = tp / (tp + fn) if (tp + fn) > 0 else 0

        precisions.append(precision)
        recalls.append(recall)

    auc_pr = 0
    for i in range(1, len(recalls)):
        auc_pr += (recalls[i] - recalls[i-1]) * (precisions[i] + precisions[i-1]) / 2

    return auc_pr

In [81]:
y_test.iloc[0]

np.int64(1)

In [82]:
log_reg_auc_pr_important_features = calculate_auc_pr(y_test, log_reg_important_features.predict_proba(X_test_important_features)[:,1])
knn_auc_pr_important_features = calculate_auc_pr(y_test, knn_important_features.predict_proba(X_test_important_features)[:,1])
naive_baues_auc_pr_important_features = calculate_auc_pr(y_test, naive_baues_important_features.predict_proba(X_test_important_features)[:,1])

print(f'По топ 150 важным признакам на test:')
print(f'Logistic Regression auc_pr: {log_reg_auc_pr_important_features}')
print(f'KNN auc_pr: {knn_auc_pr_important_features}')
print(f'Gaussian Naive Bauys auc_pr: {naive_baues_auc_pr_important_features}')

По топ 150 важным признакам на test:
Logistic Regression auc_pr: 0.4099215194994629
KNN auc_pr: 0.3688255754484181
Gaussian Naive Bauys auc_pr: 0.3189418115160606

# Which hard label metric do you prefer for the task of detecting "lemon" cars?

Я думаю неплохо будет использовать Recall, так как нам важнее найти все машины, которые истинно лимонног цвета, и если мы не лимонные тоже выберем, то не потеряем много, зато не упустим истинно лимонные, так как их не так уж и много.